### ISSUE TITLE
Can't call (overloaded) C++ operators with @cxx

### ISSUE THREAD

**Issue by zenna** [Keno/Cxx.jl#102]
A C++ library I am wrapping has many overloaded operators, e.g.

```C++
Interval operator+(const Interval& x1, const Interval& x2);
Interval operator-(const Interval& x1, const Interval& x2);
Interval operator*(const Interval& x1, const Interval& x2);
```

However, neither of the following work in Cxx.jl

```julia
+(x::Interval,y::Interval) = @cxx operator+(x.data,y.data)
+(x::Interval,y::Interval) = @cxx x.data+y.data
```

Where my `Interval` is just a type which wraps the `CppType`.  Is there currently a way to do this?

**Comment by Keno** [comment]
No, but this should be easy to fix.

**Comment by Keno** [comment]
FWIW, I have implemented this, but ran into https://github.com/JuliaLang/julia/issues/11366 while testing, so I'll wait for the to get resolved to make sure the patch didn't mess anything else up.

**Comment by Keno** [comment]
Should be fixed on master now.

**Comment by zenna** [comment]
What's the correct syntax?

I got an `unimplemented` error for `=` (The library I am using has overloaded `=`).

And for `[]`, as in: 

```julia
type CMClause
  cxx::Cxx.CppValue
end
...
@cxx clause.cxx[i-1]
```

Gives the following error

```
ERROR: LoadError: LoadError: Unrecognized CPP Expression clause.cxx[i - 1] (ref)
```

**Comment by drewrobson** [comment]
I also ran into this issue, with a library that overloaded `==` (the library allows comparing an object of type `Error` with an enum of type `ErrorType`).

The following evaluates to `true`
```
icxx"""$error_object == Library::ERROR_OK"""
```
but this evaluates to `false`:
```
@cxx error_object == Library::ERROR_OK
```
