### ISSUE TITLE
Error while building Cxx: error: no matching member function for call to 'CreateCall'

### ISSUE THREAD

**Issue by arnaudmgh** [Keno/Cxx.jl#106]
I followed the instructions for building, I built Julia with the `Make.users` file as specified. Julia is working, but `Pkg.build("Cxx")` fails. Any hint would be appreciated. 

               _
           _       _ _(_)_     |  A fresh approach to technical computing
          (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
           _ _   _| |_  __ _   |  Type "help()" for help.
          | | | | | | |/ _` |  |
          | | |_| | | | (_| |  |  Version 0.4.0-dev+4998 (2015-05-26 02:12 UTC)
         _/ |\__'_|_|_|\__'_|  |  Commit 116238c (0 days old master)
        |__/                   |  x86_64-apple-darwin13.4.0

        julia> Pkg.clone("https://github.com/Keno/Cxx.jl.git")
        INFO: Initializing package repository /Users/arnaud/.julia/v0.4
        INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
        INFO: Cloning Cxx from https://github.com/Keno/Cxx.jl.git
        INFO: Computing changes...

        julia> Pkg.build("Cxx")
        INFO: Building Cxx
        Tuning for julia installation at: /install/julia/julia/usr/bin
            CC /Users/arnaud/.julia/v0.4/Cxx/deps/build/bootstrap.o
        ../src/bootstrap.cpp:205:17: error: no matching member function for call to
              'CreateCall'
                builder.CreateCall(ctor.Initializer);
                ~~~~~~~~^~~~~~~~~~
        /install/julia/julia/usr/bin/../../usr/include/llvm/IR/IRBuilder.h:1468:13: note: 
              candidate function not viable: requires at least 2 arguments, but 1 was
              provided
          CallInst *CreateCall(Value *Callee, ArrayRef<Value *> Args,
                    ^
        /install/julia/julia/usr/bin/../../usr/include/llvm/IR/IRBuilder.h:1473:13: note: 
              candidate function not viable: requires at least 3 arguments, but 1 was
              provided
          CallInst *CreateCall(llvm::FunctionType *FTy, Value *Callee,
                    ^
        /install/julia/julia/usr/bin/../../usr/include/llvm/IR/IRBuilder.h:1478:13: note: 
              candidate function not viable: requires at least 2 arguments, but 1 was
              provided
          CallInst *CreateCall(Function *Callee, ArrayRef<Value *> Args,
                    ^
        1 error generated.
        make: *** [build/bootstrap.o] Error 1
        =================================[ ERROR: Cxx ]=================================

        LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/install/julia/julia/usr/bin`, ProcessExited(2)) [2]
        while loading /Users/arnaud/.julia/v0.4/Cxx/deps/build.jl, in expression starting on line 16

        ================================================================================

        ================================[ BUILD ERRORS ]================================

        WARNING: Cxx had build errors.

         - packages with build errors remain installed in /Users/arnaud/.julia/v0.4
         - build the package(s) and all dependencies with `Pkg.build("Cxx")`
         - build a single package by running its `deps/build.jl` script

        ================================================================================

**Comment by Keno** [comment]
I have a fix, but I'm still running into julia bugs, so I don't want to put it onto master in case it's my fault. The kf/bug branch is the latest one I have, try that.

**Comment by arnaudmgh** [comment]
Thank you! I figured I should go to `~/.julia/v0.4` and run

    $> git fetch
    $> git checkout origin/kf/bug

This problem is behind me now; it is just that now, I get    
     
     julia> Pkg.build("Cxx")
    INFO: Building Cxx
    CC /Users/arnaud/.julia/v0.4/Cxx/deps/build/bootstrap.o
    LINK /Users/arnaud/.julia/v0.4/Cxx/deps/usr/lib/libcxxffi.dylib
    Tuning for julia installation at: /install/julia/julia/usr/bin
    Not building debug library because corresponding julia DEBUG library does not exist.
    To build, simply run the build again once the library at
    /install/julia/julia/usr/bin/../../usr/lib/libjulia-debug.dylib
    has been built.

I am on Mac OS 10.9.5, mac book pro (intel core i5).

**Comment by Keno** [comment]
That's fine, it's just a note that you're only running the release version.

**Comment by arnaudmgh** [comment]
I thought it was the case, so I tried the first commands of the readme and got 


     julia> using Cxx
	ERROR: LoadError: could not open file /Users/arnaud/.julia/v0.4/Cxx/src/autowrap.jl
	 in include at ./boot.jl:252
	 in include_from_node1 at ./loading.jl:133
	 in include at ./boot.jl:252
	 in include_from_node1 at ./loading.jl:133
	 in reload_path at ./loading.jl:157
	 in _require at ./loading.jl:69
	 in require at ./loading.jl:53
	while loading /Users/arnaud/.julia/v0.4/Cxx/src/Cxx.jl, in expression starting on line 161

	julia> using Cxx

	julia> cxx""" #include<iostream> """
	ERROR: BoundsError: attempt to access 0-element Array{Cxx.ClangCompiler,1}
	  at index [1]

Which made me think it was a problem. I guess this is another problem, unrelated.

**Comment by arnaudmgh** [comment]
So I commented `include("autowrap.jl")` at line 161 of `Cxx.jl` and now it works.
