### ISSUE TITLE
@cxx cannot take address of value made by @cxx

### ISSUE THREAD

**Issue by drewrobson** [Keno/Cxx.jl#120]
`@cxx` won't let me take the address of a value that I made using `@cxx`. It works fine if I made the value on the C++ side:

```
cxx"""
class Foo {};
Foo foo; 
"""
@cxx &foo # works

foo2 = @cxx Foo()
@cxx &foo2 # LoadError: Could not find foo2 in translation unit
```

**Comment by Keno** [comment]
I don't know of a good way to make this work with `@cxx`, but `icxx" &$foo2; " should work.

**Comment by drewrobson** [comment]
Yes, I have been using `icxx" &$foo2; " as a workaround for now.

I think the cxx macro could just branch on isdefined(name). This (messy) example seems to work:

```
macro address(name)
    name_str = string(name)
    isdefined(name) ? Cxx.process_cxx_string("&\$$name_str;", false, false) : Cxx.process_cxx_string("&$name_str;", false, false)
end
@address foo # works
@address foo2 # works
```

**Comment by Keno** [comment]
No, the `@cxx` macro interprets that symbol in the C++ namespace. It should not look at julia symbols.

**Comment by Keno** [comment]
Once the special parsing for unary `&` is gone, I can make this a method of `&`, but until then I think the `icxx` method is the best way to go.

**Comment by drewrobson** [comment]
Thank you for the explanation. I understand now that `&` should be handled on the Julia side, and not by `@cxx`. The `&` method sounds like a great long term solution.

Would it make sense to define a `pointer` method that converts a CppValue to CppPtr? Otherwise I will just use `icxx`. Sorry for belaboring this!

**Comment by Keno** [comment]
Yes, I can add such a function.

**Comment by drewrobson** [comment]
Thanks!
