### ISSUE TITLE
Syntax for saving the result in a variable at the C++ REPL

### ISSUE THREAD

**Issue by Keno** [Keno/Cxx.jl#124]
The following is a fairly common pattern and is annoying
```
C++ > $frame->GetVariableList(false)
Cxx.CppPtr{Cxx.CppValue{Cxx.CppBaseType{symbol("lldb_private::VariableList")},(false,false,false)},(false,false,false)}(Ptr{Void} @0x0000000013c79730)

julia> VL = ans
Cxx.CppPtr{Cxx.CppValue{Cxx.CppBaseType{symbol("lldb_private::VariableList")},(false,false,false)},(false,false,false)}(Ptr{Void} @0x0000000013c79730)
```

**Comment by Keno** [comment]
I'm getting partial to the idea of making
```
C++> a = foo()
```
do this. Of course that would conflict with assignment syntax for globals, but perhaps we could check the list of all globals known to C++.

**Comment by ScottPJones** [comment]
Maybe explicitly mark assignment to C or C++ globals variables, or to Julia variables? Something like `silly := foo ()`
I think that would be much simpler and easier to explain to people.

**Comment by Keno** [comment]
Seems like a reasonable idea. I'll try it out and see how if feels.
