### ISSUE TITLE
Pkg.build("Cxx") Error: /usr/bin/ld: cannot find -lz 

### ISSUE THREAD

**Issue by TeroFrondelius** [Keno/Cxx.jl#125]
Hi 
I got this output:
```
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [usr/lib/libcxxffi.so] Error 1
```
I edited the ~/.julia/v0.4/Cxx/deps/BuildBootstrap.Makefile line:
```
JULIA_LDFLAGS = -L$(build_shlibdir) -L$(build_libdir) -L/home/tero/anaconda/lib/
```
Now it works, but it looks like a workaround. From a new user point of view, the easiest fix would be to add the libz to the deps and build from source. Minimum "demand" would be to list this dependency in https://github.com/Keno/Cxx.jl#build-requirements

**Comment by Keno** [comment]
libz is an optional llvm dependency. If it tries to link to it that must mean it detected it during configuration and then somehow lost it. If it's not linked that's probably either a julia or an LLVM bug, so I'll close this here. If you can look at the LLVM configuration log, it might tell you where it thought it was, which would be helpful to track down why it can't find it now. You can post that here and I can have a look at where to file this properly.

**Comment by TeroFrondelius** [comment]
@Keno is this the right place?
```
tero@tero-Dell-System-XPS-L321X ~/dev/julia_Cxx/julia/deps/llvm-svn $ grep -i "libz" config.log 
HAVE_LIBZ='0'
tero@tero-Dell-System-XPS-L321X ~/dev/julia_Cxx/julia/deps/llvm-svn $ grep "\-lz" config.log 
configure:9940: checking for compress2 in -lz
configure:9975: clang -o conftest    conftest.c -lz  -lpthread -ledit -ltinfo -ldl -lm  >&5
/usr/bin/ld: cannot find -lz
tero@tero-Dell-System-XPS-L321X ~/dev/julia_Cxx/julia/deps/llvm-svn $ 
```
