### ISSUE TITLE
Pkg.register("Cxx") and Pkg.publish()

### ISSUE THREAD

**Issue by TeroFrondelius** [Keno/Cxx.jl#132]
I understand that currently this is not possible or there is no easy way of doing this, while using the svn version of LLVM. Of course this affects also all the packages, which use Cxx.jl. 

Here is our issue https://github.com/JuliaFEM/MiniBall.jl/issues/1

@Keno do you know which future release of julia will use correct LLVM version and Cxx.jl can be added to METADATA.jl?

**Comment by ihnorton** [comment]
See https://github.com/JuliaLang/julia/issues/7737

(as far as getting Julia on a newer version of LLVM, see https://github.com/JuliaLang/julia/issues/9336 ... the timing of that is not certain, but hopefully will happen early in the 0.5 cycle)

**Comment by Keno** [comment]
This is done.
