### ISSUE TITLE
undefined reference in libcxxffi.so when `using Cxx`

### ISSUE THREAD

**Issue by cdsousa** [Keno/Cxx.jl#134]
I'm getting the following error

    julia> using Cxx
    ERROR: LoadError: LoadError: could not load library 'libcxxffi'
    /home/csousa/.julia/v0.4/Cxx/src/../deps/usr/lib/libcxxffi.so: undefined symbol: _ZN24RegisterContextPOSIX_arm22InvalidateAllRegistersEv
     in init_libcxxffi at /home/csousa/.julia/v0.4/Cxx/src/initialization.jl:20
     in include at ./boot.jl:254
     in include_from_node1 at ./loading.jl:133
     in include at ./boot.jl:254
     in include_from_node1 at ./loading.jl:133
     in reload_path at ./loading.jl:157
     in _require at ./loading.jl:69
     in require at ./loading.jl:52
    while loading /home/csousa/.julia/v0.4/Cxx/src/initialization.jl, in expression starting on line 22
    while loading /home/csousa/.julia/v0.4/Cxx/src/Cxx.jl, in expression starting on line 156

after a successful build of Julia (Commit 0eae746, with Make.user given by Cxx instructions) and a successful Pkg.build of Cxx (Commit a991318). (My system is a x86_64 Ubuntu 15.04)

Am I doing something wrong?

**Comment by Keno** [comment]
No, this is my bad. I'll have a fix shortly.

**Comment by Keno** [comment]
This is fixed, but you'll also need to update LLDB to make sure https://github.com/llvm-mirror/lldb/commit/ae8123f01c328d4091ea6f7799e274d1bdff6033 is included.

**Comment by cdsousa** [comment]
Thanks Keno. Thank you for all the work you've putting on this.

It worked with just an issue: `using CXX` complained about CLang:

    WARNING: Could not add directory /....../julia/usr/bin/../lib/clang/3.7.0/include/ to clang search path!

After a `ln -s /....../julia/usr/bin/../lib/clang/3.8.0 /....../julia/usr/bin/../lib/clang/3.7.0` it worked OK.
