### ISSUE TITLE
compile fails v0.3.0-rc3-6738-g181c19f 

### ISSUE THREAD

**Issue by steven-varga** [Keno/Cxx.jl#138]
Hi,

with the most recent version of Julia dev branch and the suggested settings compilation fails on Linux Mint 17

any suggestions?
best,
steve

override LLDB_VER=master
override LLVM_VER=svn
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override BUILD_LLDB=1
override USE_LLVM_SHLIB=1
override LLDB_DISABLE_PYTHON=1

llvm[7]: Installing Release+Asserts Archive Library /home/steven/src/julia/usr-staging/llvm-svn/build_Release+Asserts/home/steven/src/julia/usr/lib/liblldbPluginJITLoaderGDB.a
llvm[6]: Compiling ClangASTContext.cpp for Release+Asserts build
In file included from /home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:8841:0:
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/../../source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h: In member function ‘virtual lldb::TypeSP lldb_private::ClangASTContext::ParseTypeFromDWARF(const lldb_private::SymbolContext&, SymbolFileDWARF*, DWARFCompileUnit*, const DWARFDebugInfoEntry*, lldb_private::Log*, bool*)’:
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/../../source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h:285:5: error: ‘lldb::TypeSP SymbolFileDWARFDebugMap::FindCompleteObjCDefinitionTypeForDIE(const DWARFDebugInfoEntry*, const lldb_private::ConstString&, bool)’ is protected
     FindCompleteObjCDefinitionTypeForDIE (const DWARFDebugInfoEntry *die, 
     ^
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:11238:134: error: within this context
                                     type_sp = debug_map_symfile->FindCompleteObjCDefinitionTypeForDIE (die, type_name_const_str, true);
                                                                                                                                      ^
In file included from /home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:8841:0:
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/../../source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h:279:5: error: ‘lldb::TypeSP SymbolFileDWARFDebugMap::FindDefinitionTypeForDWARFDeclContext(const DWARFDeclContext&)’ is protected
     FindDefinitionTypeForDWARFDeclContext (const DWARFDeclContext &die_decl_ctx);    
     ^
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:11296:113: error: within this context
                                 type_sp = debug_map_symfile->FindDefinitionTypeForDWARFDeclContext (die_decl_ctx);
                                                                                                                 ^
In file included from /home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:8841:0:
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/../../source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h:190:5: error: ‘static uint32_t SymbolFileDWARFDebugMap::GetOSOIndexFromUserID(lldb::user_id_t)’ is protected
     GetOSOIndexFromUserID (lldb::user_id_t uid)
     ^
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:11822:170: error: within this context
                                             class_symfile = debug_map_symfile->GetSymbolFileByOSOIndex(SymbolFileDWARFDebugMap::GetOSOIndexFromUserID(class_type->GetID()));
                                                                                                                                                                          ^
In file included from /home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:8841:0:
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/../../source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h:230:5: error: ‘SymbolFileDWARF* SymbolFileDWARFDebugMap::GetSymbolFileByOSOIndex(uint32_t)’ is protected
     GetSymbolFileByOSOIndex (uint32_t oso_idx);
     ^
/home/steven/src/julia/deps/llvm-svn/tools/lldb/source/Symbol/ClangASTContext.cpp:11822:171: error: within this context
                                             class_symfile = debug_map_symfile->GetSymbolFileByOSOIndex(SymbolFileDWARFDebugMap::GetOSOIndexFromUserID(class_type->GetID()));
                                                                                                                                                                           ^
/bin/rm: cannot remove ‘/home/steven/src/julia/deps/llvm-svn/build_Release+Asserts/tools/lldb/source/Symbol/Release+Asserts/ClangASTContext.d.tmp’: No such file or directory
make[6]: *** [/home/steven/src/julia/deps/llvm-svn/build_Release+Asserts/tools/lldb/source/Symbol/Release+Asserts/ClangASTContext.o] Error 1
make[5]: *** [Symbol/.makeinstall] Error 2
make[4]: *** [install] Error 1
make[3]: *** [install] Error 1
make[2]: *** [install] Error 1
make[1]: *** [/home/steven/src/julia/usr/lib/libLLVMCodeGen.a] Error 2
make: *** [julia-deps] Error 2

**Comment by ihnorton** [comment]
This actually looks like an upstream issue, as the build errors are not in Cxx. Presumably they will be fixed soon, so you should try running `make -C deps update-llvm` from the Julia directory.

**Comment by Keno** [comment]
I made two fixes to julia and Cxx, but am now able to build everything again. Please try again.

**Comment by steven-varga** [comment]
Thank you! 
I was able to compile Julia commit e33486d62e2919e73e68772667d1d8b4de350ad5 with llvm-svn commit e45daf6294839dc0a06a20eb1fe434a61ae6336a

best,
steve
