### ISSUE TITLE
Errors when initializing Cxx on Mac OS X

### ISSUE THREAD

**Issue by pazzo83** [Keno/Cxx.jl#140]
I built Julia 0.4 from source, using the Make.user overrides specified, and then cloned and built the Cxx package using the package manger.  However, when I run "using Cxx", I get the following error:

ERROR: InitError: cfunction: no method exactly matched the required type signature (function not yet c-callable)
 in __init__ at /Users/christopheralexander/.julia/v0.4/Cxx/src/initialization.jl:328
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267
 in require at ./loading.jl:206
during initialization of module Cxx

Any ideas?

Thanks!

**Comment by Keno** [comment]
This was a bug in Julia which I fixed earlier today. Try updating Julia.

**Comment by pazzo83** [comment]
Nice, rebuilt and got it working!!  Although, when I run "using Cxx", I see this printed about 4 times:
In file included from :1:
In file included from __cxxjl_1.cpp:5:
In file included from /Users/christopheralexander/Julia/latest/julia/usr/bin/../include/clang/Parse/Parser.h:24:
In file included from /Users/christopheralexander/Julia/latest/julia/usr/bin/../include/clang/Sema/Sema.h:18:
In file included from /Users/christopheralexander/Julia/latest/julia/usr/bin/../include/clang/AST/Attr.h:18:
In file included from /Users/christopheralexander/Julia/latest/julia/usr/bin/../include/clang/AST/Decl.h:29:
/Users/christopheralexander/Julia/latest/julia/usr/bin/../include/llvm/Support/TrailingObjects.h:101:19: error: no member named 'is_final' in namespace 'std'
    static_assert(LLVM_IS_FINAL(BaseTy), "BaseTy must be final.");
                  ^~~~~~~~~~~~~~~~~~~~~
/Users/christopheralexander/Julia/latest/julia/usr/bin/../include/llvm/Support/type_traits.h:100:32: note: expanded from macro 'LLVM_IS_FINAL'
#define LLVM_IS_FINAL(Ty) std::is_final<Ty>()

However, seems to work fine in the Julia REPL (I was running some of the examples you have in the README).  I'll try some other things later.

Thanks!

**Comment by Keno** [comment]
I think @nkottary fixed this in #147.
