### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by MithrandirMiles** [Keno/Cxx.jl#153]
The README talks about 0.4-dev, however, that should now be 0.4-pre.
The instructions talk about setting `LLVM_VER=svn`, however, since `3.7.0` has been released,
should it specify `LLVM_VER=3.7.0` instead?

Finally, I tried to submit an issue and fork `Cxx.jl` (in order to submit a PR later to update this), but my normal account at-ScottPJones seems to be blocked on that repository.

**Comment by Keno** [comment]
> The instructions talk about setting LLVM_VER=svn, however, since 3.7.0 has been released,
> should it specify LLVM_VER=3.7.0 instead?

No, Cxx.jl continues to target llvm svn.

**Comment by MithrandirMiles** [comment]
What hasn't been fixed in 3.7.0 that is needed for Cxx.jl?
3.7.0 builds fine for me on OS X 10.11, but svn is having some problems.

**Comment by admsyn** [comment]
I'm also having an issue w/ llvm-svn fwiw (OS X 10.10) 

```
llvm[7]: Compiling DisassemblerLLVMC.cpp for Release+Asserts build
/Users/adam/workspace/julia/deps/llvm-svn/tools/lldb/source/Plugins/Disassembler/llvm/DisassemblerLLVMC.cpp:560:17: error: attempt to use a deleted function
    inst_stream.flush();
                ^
/Users/adam/workspace/julia/deps/llvm-svn/include/llvm/Support/raw_ostream.h:512:8: note: 'flush' has been explicitly marked deleted here
  void flush() = delete;
       ^
1 error generated.
make[7]: *** [/Users/adam/workspace/julia/deps/llvm-svn/build_Release+Asserts/tools/lldb/source/Plugins/Disassembler/llvm/Release+Asserts/DisassemblerLLVMC.o] Error 1
make[6]: *** [Disassembler/llvm/.makeinstall] Error 2
make[5]: *** [Plugins/.makeinstall] Error 2
make[4]: *** [install] Error 1
make[3]: *** [install] Error 1
make[2]: *** [install] Error 1
make[1]: *** [/Users/adam/workspace/julia/usr/lib/libLLVMCodeGen.a] Error 2
make: *** [julia-deps] Error 2
```

**Comment by Keno** [comment]
Build issues should be solved (needs latest LLVM though).
