### ISSUE TITLE
Method lookup_name throws error

### ISSUE THREAD

**Issue by ibadami** [Keno/Cxx.jl#164]
Hi,

I am using julia master with LLVM=svn on ubuntu 14.04. I recently try to use OpenCV.jl. For which I installed Cxx.jl and OpenCV3 master. 
After successfully installing Cxx.jl when I am trying to use OpenCV.jl I get following error.

```
julia> cvRect(5,5,300,300)
ERROR: Could not find Rect in context cv
 in error at ./error.jl:21
 in lookup_name at /home/badami/.julia/v0.5/Cxx/src/typetranslation.jl:116

```

I reported this error in OpenCV.jl https://github.com/maxruby/OpenCV.jl/issues/3
The author of the library works on OSX 10.10.5 with Julia master and LLVM=svn and can successfully run OpenCV.jl . 

Is it possible that this error is related to clang library in ubuntu?

**Comment by Keno** [comment]
Usually means the headers aren't loaded correctly. Try just running code at the C++ prompt and seeing if that works (`<` key).

**Comment by ibadami** [comment]
Headers of which library?

**Comment by Keno** [comment]
I was talking about the OpenCV headers. I'm not sure how OpenCV.jl deals with that, but I have used OpenCV before with the more minimal wrapper here: https://github.com/Keno/OCV.jl
```
julia> using OCV

C++> cv::Point(5,5)
Cxx.CppValue{Cxx.CxxQualType{Cxx.CppTemplate{Cxx.CppBaseType{symbol("cv::Point_")},Tuple{Int32}},(false,false,false)},8}((0x05,0x00,0x00,0x00,0x05,0x00,0x00,0x00))

```

**Comment by maxruby** [comment]
`OpenCV.jl` deals just fine loading headers for OSX (I tested it on OSX 10.10.5 with julia-0.5dev and latest Cxx.jl). It has never been optimized for Linux users. There has not been a consistent way to handle the loading of the headers and libs, and although some Linux users proposed certain solutions, I can't further test how well these work because I do not work with Linux.

**Comment by ibadami** [comment]
@Keno I see. I have tried the OCV package.
While building the package I get the following error.

```
julia> Pkg.build("OCV")
INFO: Building OCV
==========================================[ ERROR: OCV ]===========================================

LoadError: None of the selected providers can install dependency opencv_test.
Use BinDeps.debug(package_name) to see available providers

while loading /home/badami/.julia/v0.5/OCV/deps/build.jl, in expression starting on line 21

===================================================================================================

=========================================[ BUILD ERRORS ]==========================================

WARNING: OCV had build errors.

 - packages with build errors remain installed in /home/badami/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("OCV")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================

```

I do not have opencv_text module in my opencv3 github copy. I could not find it anywhere on internet as well. So I removed the dependency from build.jl to see what happens next.
It builds fine then, but when I type <code>using OCV</code> I get this error:

```
julia> using OCV
ERROR: LoadError: ArgumentError: FixedSizeArrays not found in path
 in require at ./loading.jl:233
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
while loading /home/badami/.julia/v0.5/OCV/src/OCV.jl, in expression starting on line 3

```

Do you think this is related to opencv headers?
It does find the libraries alright:

```
julia> BinDeps.debug("OCV")
INFO: Reading build script...
The package declares 4 dependencies.
 - Library "opencv_core"
    - Satisfied by:
      - System Paths at /usr/local/lib/libopencv_core.so
 - Library "opencv_highgui"
    - Satisfied by:
      - System Paths at /usr/local/lib/libopencv_highgui.so
 - Library "opencv_imgproc"
    - Satisfied by:
      - System Paths at /usr/local/lib/libopencv_imgproc.so.3.0
 - Library "opencv_objdetect"
    - Satisfied by:
      - System Paths at /usr/local/lib/libopencv_objdetect.so
```

**Comment by ibadami** [comment]
@Keno and @maxruby 

After Keno suggested I closely look at OpenCV.jl file to find out how it loads the header files of OpenCV.
And guess what there is a typo in the line 67 where it suppose to add headers of the opencv

```
addHeaderDir(cvlibdir; kind = C_System)

``` 
where <code>cvlibdir</code> is defined as  <code>const cvlibdir = "/usr/local/lib/"</code>

Instead it should be 

```
addHeaderDir(cvheaderdir; kind = C_System)

```
where <code>cvheaderdir</code> is defined  <code>const cvheaderdir = "/usr/local/include/"</code>

After making that correction, things are working for me :) :) :)

Thanks a lot you both.
