### ISSUE TITLE
Wrapping C++ References?

### ISSUE THREAD

**Issue by malex984** [Keno/Cxx.jl#169]
Could you please add an example for wrapping C++ functions with references
and how to call them with Julia values, e.g. as follows:

```
using Cxx
cxx""" void inp(int &x){ x += 1; };  """
x = 666
@cxx inp(x)
x  # expected: 667  
```

Thanks in advance!

**Comment by Keno** [comment]
Well, clearly it can't mutate, immutables. You can definitely use an array and dereference. However, I think I can probably just make it work with `Ref`. Hold on.

**Comment by Keno** [comment]
This works now:
```
julia> using Cxx

julia> cxx""" void inp169(int &x){ x += 1; };  """
true

julia> x169 = Ref{Cint}(666)
Base.RefValue{Int32}(666)

julia> icxx"inp169($x169);"

julia> @assert x169[] == 667

julia> x169[]
667
```

**Comment by malex984** [comment]
Thanks a lot! 
BTW, i somehow expected that `@cxx inp169(x169)` would boil down to  `icxx"inp169($x169);`", but:

```
julia> @cxx inp169(x169)
ERROR: Got bad type information while compiling Cxx.CppNNS{Tuple{:inp169}} (got Base.RefValue{Int32} for argument 1)
 in error at ./error.jl:21
 in check_args at $HOME/.julia/v0.5/Cxx/src/codegen.jl:431
```

Is it to be expected? Is there any workaround to use references via `@cxx` ?

**Comment by Ken-B** [comment]
@Keno What's the current way to do this? Your example no longer runs.

Perhaps you could add this example to the Readme?

Thank you for your time.
