### ISSUE TITLE
Assertion failure when creating a template function

### ISSUE THREAD

**Issue by malmaud** [Keno/Cxx.jl#171]
C++ > C++ > namespace jon {
            template<typename T> T g(T val) {return val+1;}
            }
      Assertion failed: (Ctx->isFileContext() && "We should have been looking only at file context here already."), function CppLookupName, file /Users/malmaud/julia_cxx/deps/srccache/llvm-svn/tools/clang/lib/Sema/SemaLookup.cpp, line 1237.

**Comment by Keno** [comment]
I assume that was supposed to be:
```
C++ > namespace jon {
      template < typename T > g(T val) {return val+1;}
      }
Assertion failed: (Ctx->isFileContext() && "We should have been looking only at file context here already."), function CppLookupName, file /Users/kfischer/Projects/julia-testpatch/deps/srccache/llvm-svn/tools/clang/lib/Sema/SemaLookup.cpp, line 1237.
```
If so I can reproduce :)

**Comment by Keno** [comment]
Note that the well formed
```
C++ > namespace jon {
      template < typename T > T g(T val) {return val+1;}
      }
true
```
does work.

**Comment by Keno** [comment]
Hmm, actually I rebuilt Cxx and now I can't reproduce any more. Odd...

**Comment by malmaud** [comment]
Ah woops.

**Comment by Keno** [comment]
Yeah, I can't reproduce this anymore. Can you?

**Comment by malmaud** [comment]
Nope, guess it was fixed at some point.
