### ISSUE TITLE
Error when importing: no type named 'length_error'  in namespace 'std'

### ISSUE THREAD

**Issue by gpascualg** [Keno/Cxx.jl#173]
When doing `using Cxx`, the following shows up:

```
In file included from :1:
__cxxjl_2.cpp:1:6: error: no type named 'length_error' in namespace 'std'
std::length_error&
~~~~~^
ERROR: LoadError: LoadError: Could not parse type name
 in ParseTypeName at /home/guillem/.julia/v0.5/Cxx/src/initialization.jl:103
while loading /home/guillem/.julia/v0.5/Cxx/src/std.jl, in expression starting on line 20
while loading /home/guillem/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 170
```

Cxx is not working afterwards. If I reimport it, it won't complain again, but still it won't work properly.

For example, writing `cxx""" #include<iostream> """ `
Results in: http://pastebin.com/ijYTLmmR

Last time I checked Cxx with Julia `0.4-dev`, same GCC version, it used to work. A recent install on `release-0.4` does work too (same GCC version).

Updating GCC is, sadly, not an option, but installing clang might be.

-----

Julia:
```
Version 0.5.0-dev+571 (2015-10-02 08:14 UTC)
Commit 71e51ec* (0 days old master)
x86_64-linux-gnu
```

Cxx: b7a458e358f738e1e06a7eb2771c81e9351cbc7f

GCC: 
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
```

Built with `Make.user`:
```
override LLDB_VER=master
override LLVM_VER=svn
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override BUILD_LLDB=1
override USE_LLVM_SHLIB=1
override LLDB_DISABLE_PYTHON=1
```

`uname -a`:
```
Linux guillem-elementary-desk 3.16.0-48-generic #64~14.04.1-Ubuntu SMP Thu Aug 20 23:03:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by maxj** [comment]
Not much of a help, but I am seeing this as well.  I have not gotten Cxx to run successfully.

```julia
using Cxx
In file included from :1:
__cxxjl_2.cpp:1:6: error: no type named 'length_error' in namespace 'std'
std::length_error&
~~~~~^
ERROR: LoadError: LoadError: Could not parse type name
 in ParseTypeName at /home/maxj/.julia/v0.5/Cxx/src/initialization.jl:104
while loading /home/maxj/.julia/v0.5/Cxx/src/std.jl, in expression starting on line 20
while loading /home/maxj/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 170
```

I tried to debug a little further but have not gotten anywhere and am probably over my head.

It looks like cxxstr.jl iterates through a list of standard library headers in the CxxTypeName function.  It goes through std::string and std::vector successfully but chokes on std::length_error&.  I've checked and stdexcept is included on the paths in initialize.jl

```
ls -la /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8 | grep stdexcept
-rw-r--r--  1 root root  4718 May 14 14:11 stdexcept
```

I'm running Ubuntu 14.04, julia commit: bcc3736d.  (I'm getting a codegen error on julia head + llvm head, but that should be unrelated) 

Anyone see this before?

**Comment by maxj** [comment]
I tried again with a fresh build off the main kf/gallium branch with the suggested patch.  Same error.  I suppose this is a Ubuntu specific problem.  Any ideas where I should be looking to start debugging?

**Comment by Keno** [comment]
Easiest thing that could go wrong is that there's a header that needs to be included on Ubuntu, but not mac

**Comment by maxjordan** [comment]
Ok  - something must be messed up in my includes - std::string and std::vector seem to be ok, but length_error is missing.  If I ignore the hunt for std::length_error, this works fine.  I'll try to see if I can modify initialization.jl to pick up the additional includes.

**Comment by Keno** [comment]
I just meant the header might be missing from a `#include`. I think we explicitly `#include <vector>` somewhere, which would explain this.

**Comment by maxj** [comment]
Ah - great.  Got this working now, thanks.  Thanks for your help!

**Comment by Keno** [comment]
Great!
