### ISSUE TITLE
build fails with jl_ExecutionEngine not found

### ISSUE THREAD

**Issue by jpata** [Keno/Cxx.jl#186]
`Pkg.build("Cxx")` recently started failing with `jl_ExecutionEngine` not being found. Seems like julia doesn't export it any more to `libjulia`.

**Comment by jpata** [comment]
The following
~~~
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -322,9 +322,8 @@ private:
 static JuliaOJIT *jl_ExecutionEngine;
 #else
 #if !defined(LLVM35) || defined(LLVM36)
-static
 #endif
-  ExecutionEngine *jl_ExecutionEngine;
+DLLEXPORT ExecutionEngine *jl_ExecutionEngine;
 #endif
~~~
seems to fix but don't know if reasonable.

**Comment by Keno** [comment]
Yeah, should be exported. Jameson keeps removing that

**Comment by Keno** [comment]
Fixed upstream.
