### ISSUE TITLE
Extract value from CppRef to non-built-in type

### ISSUE THREAD

**Issue by malmaud** [Keno/Cxx.jl#189]
If I have a CppRef to an instance of a custom C++ class, what is the recommended way of dereferencing it and getting back a CppValue to the underlying instance? 

I can see how to do through manually by loading the the right number of bytes from the CppRef `ptr` field and explicitly constructing a `CppValue` with those bytes, but is there an API for that?

**Comment by Keno** [comment]
Something like
```
function deref(x)
icxx"""
auto r = $x;
return r;
"""
end

**Comment by malmaud** [comment]
Thanks!
