### ISSUE TITLE
Construct a std::function from a function pointer

### ISSUE THREAD

**Issue by malmaud** [Keno/Cxx.jl#190]
I want to construct an `std::function` object from a `Ptr{Void}` that was returned from `cfunction`. Calling the ``std::function`` constructor results in this pertinent error:

```
...
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2226:2: note: candidate template ignored: substitution failure [with _Functor = void *]: called object type 'void *' is not a function or function pointer
        function(_Functor);
...
```

I'm not sure how to cast the `Ptr{Void}` in such a way that it is interpreted as a function pointer.

**Comment by Keno** [comment]
The correct syntax here is:
```
C++ > (void (*)(int,double))nullptr
Cxx.CppFptr{Cxx.CppFunc{Void,Tuple{Int32,Float64}}}(Ptr{Void} @0x0000000000000000)
```

**Comment by malmaud** [comment]
Thanks! Still having some trouble getting a `std::function`, though...

```
julia> ptr=icxx"(void (*)(int,double))nullptr;"
Cxx.CppFptr{Cxx.CppFunc{Void,Tuple{Int32,Float64}}}(Ptr{Void} @0x0000000000000000)

julia> icxx"function<void(int,double)>($ptr);"
ERROR: MethodError: `length` has no method matching length(::Type{Tuple{Int32,Float64}})
 in cpptype at /root/.julia/v0.5/Cxx/src/typetranslation.jl:267
```

**Comment by malmaud** [comment]
With https://github.com/Keno/Cxx.jl/pull/191, this almost works. I can do 

`icxx"new function<void(int,double)>($ptr);"` and get back a pointer to a correct `function` object, but this returns `nothing`:

```
icxx"function<void(int,double)>($ptr);"
```

**Comment by Keno** [comment]
Yes, I saw that. I'm tracking this down. For now you can use an explicit return.

**Comment by malmaud** [comment]
Cool.

**Comment by Keno** [comment]
Turns out that situation is the `most vexing parse`. `icxx"std::function<void(int,double)>{$ptr};"` works fine.

**Comment by StefanKarpinski** [comment]
For those not familiar: https://en.wikipedia.org/wiki/Most_vexing_parse (I had to look it up).

**Comment by malmaud** [comment]
Its better than [the most dangerous game](http://www.screeninsults.com/images/the-most-dangerous-game-poster.jpg).
