### ISSUE TITLE
Dereferencing pointers in @cxx method calls

### ISSUE THREAD

**Issue by vglazer** [Keno/Cxx.jl#194]
I have two classes, `A` and `B`. `B` has a method called `f()` whose signature looks like this:

```c++
double B::f(const A & a1, const A & a2) const;
```

I'd like to be able to do something like this:

```julia
using Cxx

a1 = @cxxnew A()
a2 = @cxxnew A()
b = @cxxnew B()

val = @cxx b->f(*a1, *a2)
```

Unfortunately, this fails with the following error:

```
ERROR: LoadError: syntax: "*" is not a unary operator
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
```

One workaround is to introduce a templated method called `get_ref()` which looks like this:

```julia
cxx"""
    template<typename T>
    T & get_ref(T * t)
    {
        return *t;
    }
"""
```

With this kludge, the following works as expected:

```julia
a1_ref = @cxx get_ref(a1)
a2_ref = @cxx get_ref(a2)
value = @cxx b->f(a1_ref, a2_ref)
```

The above approach isn't very satisfying though. Is there a better way to deal with situations like this in the current implementation? 

SWIG has some special magic for handling such things, for example:
http://www.swig.org/Doc1.3/SWIGPlus.html#SWIGPlus_nn18

**Comment by vglazer** [comment]
A wise man pointed out to me that the following works:

```julia
val = @cxx b->f(*(a1), *(a2))
```

**Comment by StefanKarpinski** [comment]
This is why I dislike punning on Julia syntax to write C++ code :-\

**Comment by Keno** [comment]
I agree, I'm considering deprecating the macro syntax.

**Comment by vglazer** [comment]
`icxx"""` may be all you need if the goal is to evaluate C++ code for its side effects, but in general you would still need some mechanism for passing the return value back to Julia, right?

Is there another way to do that right now besides `@cxx`?

**Comment by Keno** [comment]
Yes, you can have a `return` in icxx and the last value is implicitly returned.

**Comment by vglazer** [comment]
That's great to know, thank you Keno!

**Comment by StefanKarpinski** [comment]
And people wonder why expression-oriented languages are nice.
