### ISSUE TITLE
Problems building with v0.4.1

### ISSUE THREAD

**Issue by JonathanAnderson** [Keno/Cxx.jl#207]
I was originally running into #206 but i didn't see that issue until just now. Instead upon closer reading of the installation instructions I decided to skip gallium support and just follow the first part of the installation instructions.

```
git clone git://github.com/JuliaLang/julia.git julia_cxx

cd julia_cxx

cat > Make.user << EOF
override LLDB_VER=master
override LLVM_VER=svn
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override BUILD_LLDB=1
override USE_LLVM_SHLIB=1
override LLDB_DISABLE_PYTHON=1
EOF

git checkout -b cxx_v0.4.1 v0.4.1

make
```

Make failed after awhile complaining it couldn't find `deps/llvm-svn/tools/lldb/test/Makefile` so I:

```
cd deps/llvm-svn/tools/lldb/test/
cmake .
make
```

This too eventually failed after `CC src/codegen.o`

I've placed the output from the first section in the following gist and the second part in the comments to the gist

https://gist.github.com/JonathanAnderson/685a203e153a2e601852

Should I wait as recommended by #206? Should I try building this off master? I'm happy to use v0.4.x or v0.5.x.

**Comment by Keno** [comment]
Please wait for a couple of days while I finish up the transition of julia master to LLVM svn. At that point all of this will be a lot simpler.

**Comment by JonathanAnderson** [comment]
Sounds great. Thanks for all the awesome work Keno.

**Comment by JonathanAnderson** [comment]
I see that you merged https://github.com/JuliaLang/julia/pull/14430  and @tkelman noted a few hours ago that 3.7.1 is out. Should i give this a try now or wait until 3.7.1 is in julia/master?

**Comment by tkelman** [comment]
On master you can set LLVM_VER to 3.7.1 and it'll use tarballs that we put up ahead of time, plus Keno's patches

**Comment by Keno** [comment]
While that's true, I do think Cxx relies on a couple LLVM 38isms at the moment. I do plan to make it compatible and build binaries once we officially switch master and have nightlies though.

**Comment by Keno** [comment]
Cxx.jl now works fine with 0.5 master, which is the supported configuration, so I'll close this issue.
