### ISSUE TITLE
Julia build error on OS X 10.11

### ISSUE THREAD

**Issue by malmaud** [Keno/Cxx.jl#216]
Seeing this error on Julia master (d4749d2) with the suggested Make.user:

```
llvm[6]: Copying runtime library darwin/eprintf to build dir
cp: /Users/malmaud/julia_master/deps/build/llvm-3.7.1/build_Release+Asserts/tools/clang/runtime/compiler-rt/clang_darwin/eprintf/libcompiler_rt.a: No such file or directory
```

**Comment by Keno** [comment]
Should be fixed with the patch I added for compiler-rt (https://github.com/JuliaLang/julia/commit/876240c74615761295e419cabf744bd5084f354d).
