### ISSUE TITLE
cxx_str not defined error appears on fresh install

### ISSUE THREAD

**Issue by dioptre** [Keno/Cxx.jl#221]
Followed the exact instructions provided in https://github.com/Keno/Cxx.jl

Only addition was PyCall

First run:

a@andyg:~/julia$ ./julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2180 (2016-01-18 00:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 54a6966* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using Cxx
ERROR: LoadError: LoadError: could not load library "libcxxffi-debug"
/home/a/.julia/v0.5/Cxx/src/../deps/usr/lib/libcxxffi-debug.so: undefined symbol: PyExc_ValueError
 [inlined code] from ./c.jl:91
 in dlopen at ./libdl.jl:66
 in init_libcxxffi at /home/a/.julia/v0.5/Cxx/src/initialization.jl:20
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in require at ./loading.jl:332
 in eval at ./boot.jl:265
while loading /home/a/.julia/v0.5/Cxx/src/initialization.jl, in expression starting on line 22
while loading /home/a/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 156

julia> using PyCall
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near no file:0
in jl_IO_seek at /home/a/.julia/v0.5/PyCall/src/io.jl
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near no file:0
in jl_IO_seek at /home/a/.julia/v0.5/PyCall/src/io.jl
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near no file:0
in jl_IO_seek at /home/a/.julia/v0.5/PyCall/src/io.jl

julia> using Cxx

julia> cxx""" #include<iostream> """
ERROR: UndefVarError: @cxx_str not defined
 in eval at ./boot.jl:265

julia> @cxx
@cxx      @cxx_mstr  @cxx_str   @cxxm      @cxxnew    @cxxt_str

julia> versioninfo()
Julia Version 0.5.0-dev+2180
Commit 54a6966* (2016-01-18 00:37 UTC)
DEBUG build
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1

**Comment by Keno** [comment]
The error means Cxx did not load correctly. I would recommend you rebuild with python disabled.

**Comment by dioptre** [comment]
Thanks - getting closer! :)

**Comment by dioptre** [comment]
...Can confirm this is not working on debian or ubuntu

**Comment by dioptre** [comment]
_       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2194 (2016-01-18 21:35 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 22851d6* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using Cxx
ERROR: LoadError: LoadError: could not load library "libcxxffi-debug"
/home/a/.julia/v0.5/Cxx/src/../deps/usr/lib/libcxxffi-debug.so: undefined symbol: jl_ExecutionEngine
 [inlined code] from ./c.jl:91
 in dlopen at ./libdl.jl:66
 in init_libcxxffi at /home/a/.julia/v0.5/Cxx/src/initialization.jl:20
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in require at ./loading.jl:332
 in eval at ./boot.jl:265
while loading /home/a/.julia/v0.5/Cxx/src/initialization.jl, in expression starting on line 22
while loading /home/a/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 156

julia> versioninfo()
Julia Version 0.5.0-dev+2194
Commit 22851d6* (2016-01-18 21:35 UTC)
DEBUG build
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
