### ISSUE TITLE
LLVM ERROR: Program used external function '_ZNK5clang8QualType11getAsStringERKNS_14PrintingPolicyE' which could not be resolved! (getAsString)

### ISSUE THREAD

**Issue by dioptre** [Keno/Cxx.jl#223]
Looking at the build:

nm -D clang | grep _ZNK5clang8QualType11getAsStringERKNS_14PrintingPolicyE

Is missing cx11 ABI

as:

 nm -D clang | grep getAsString 

gives:

00000000013a2240 T _ZNK5clang8QualType11getAsStringB5cxx11ERKNS_14PrintingPolicyE

**Comment by dioptre** [comment]
This is the culprit I think... http://stackoverflow.com/questions/33368237/undefined-reference-in-clang-when-linking-to-a-library-compiled-with-gcc5

**Comment by dioptre** [comment]
Asking on the main Julia list too as they might have more experience with ABI https://github.com/JuliaLang/julia/issues/14820

**Comment by ihnorton** [comment]
I would suggest reading the [Mozilla bug report guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines) for some suggestions on how to file a more actionable bug report. (OS? gcc version? etc.)

**Comment by dioptre** [comment]
Can confirm this **works**
**override USECLANG=1**
override LLVM_VER=3.7.1
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# For LLDB support also
override BUILD_LLDB=1
override LLDB_DISABLE_PYTHON=1

# Wahooooo

**Comment by cbecker** [comment]
Hello, I am getting the same error as above even with
`override USECLANG=1`.

My Make.user
```
#GCC >= 5 will not work
override USECLANG=1
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# Optional, but recommended
override LLVM_ASSERTIONS=1
# For LLDB support also
# override BUILD_LLDB=1
# override LLDB_DISABLE_PYTHON=1
```

and the test I am using:
```
julia> using Cxx

C++ > #include <iostream>
true

C++ > int a = 2 + 2
true

C++ > std::cout << a << std::endl
4
LLVM ERROR: Program used external function '_ZNK5clang8QualType11getAsStringERKNS_14PrintingPolicyE' which could not be resolved!
```

This is with the latest master from a few hours ago, I am not sure what is going on.

**Comment by Keno** [comment]
Did you have `USECLANG=1` set when you built LLVM?

**Comment by dioptre** [comment]
Can you make sure clang is installed too?

**Comment by cbecker** [comment]
Thanks. I cloned julia and then compiled from scratch, with that Make.user file, so LLVM was built with that flag on.

I have clang installed, running on archlinux:
```
~/github/julia-dev ᐅ clang --version
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
~/github/julia-dev ᐅ 
```

Is there any better way to check whether julia was built with clang?

**Comment by dioptre** [comment]
Well it doesn't look like it. Clang won't build your library with that ABI.... :(

Is there a way you can forcefully disable gcc? g++?

In ubuntu/debian we can run update-alternatives --config c++ /cc

**Comment by cbecker** [comment]
mm I doubt on archlinux. I will try to set CC and CXX in Make.user to point to clang, that may do.

**Comment by cbecker** [comment]
I tried again overriding CC and CXX, which now appears in `Make.config` in `deps/build/llvm-3.7.1/build_Release+Asserts`, so it looks as if LLVM is being compiled with clang:

```
# Path to the C++ compiler to use.  This is an optional setting, which defaults
# to whatever your gmake defaults to.
CXX = clang++

# Path to the CC binary, which use used by testcases for native builds.
CC := clang
```

However I still get the same error. I also tried removing Cxx completely and re-installing and re-building, with no luck. I am not sure what to try next. My `Make.user` is now
```
#GCC >= 5 will not work
override USECLANG=1
override CC=clang
override CXX=clang++
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# Optional, but recommended
override LLVM_ASSERTIONS=1
# For LLDB support also
# override BUILD_LLDB=1
# override LLDB_DISABLE_PYTHON=1
```

**Comment by cbecker** [comment]
I am not sure what is going on here. So far llvm was set up to be compiled with clang, and links to the cxx11 ABI, which I think is the only one in my system anyway:

```
~/github/julia-dev/usr/bin ᐅ nm -D clang | grep getAsString
000000000150c420 T _ZN5clang8QualType11getAsStringB5cxx11EPKNS_4TypeENS_10QualifiersE
000000000150c520 T _ZN5clang8QualType19getAsStringInternalEPKNS_4TypeENS_10QualifiersERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_14PrintingPolicyE
                 U _ZNK4llvm3opt3Arg11getAsStringB5cxx11ERKNS0_7ArgListE
000000000150bbd0 T _ZNK5clang10Qualifiers11getAsStringB5cxx11ERKNS_14PrintingPolicyE
000000000150bae0 T _ZNK5clang10Qualifiers11getAsStringB5cxx11Ev
0000000000f27840 T _ZNK5clang11LocInfoType19getAsStringInternalERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_14PrintingPolicyE
00000000015d6370 T _ZNK5clang11ObjCRuntime11getAsStringB5cxx11Ev
00000000016120c0 T _ZNK5clang12VersionTuple11getAsStringB5cxx11Ev
0000000000d58100 T _ZNK5clang14TypoCorrection11getAsStringB5cxx11ERKNS_11LangOptionsE
000000000142a8e0 T _ZNK5clang15DeclarationName11getAsStringB5cxx11Ev
000000000142b4c0 T _ZNK5clang19DeclarationNameInfo11getAsStringB5cxx11Ev
0000000000a6bff0 T _ZNK5clang20CodeCompletionString11getAsStringB5cxx11Ev
00000000013400d0 T _ZNK5clang7APValue11getAsStringB5cxx11ERNS_10ASTContextENS_8QualTypeE
000000000150c3d0 T _ZNK5clang8QualType11getAsStringB5cxx11ERKNS_14PrintingPolicyE
00000000015d0550 T _ZNK5clang8Selector11getAsStringB5cxx11Ev
```

That is from clang as compiled by julia from the source tree. I am not getting what is happening behind the scenes, why is Cxx trying to find the non-cxx11 version? I can investigate further but I don't know where to start.

**Comment by dioptre** [comment]
Try hunting for other llvm instances and dependencies on your machine and
nuke them all?

**Comment by Keno** [comment]
Some distributions of Linux have hacked clang to follow the GCC ABI. You'll either need to find that patch and apply it to julia's version of Clang as well or compile a separate upstream version of Clang with which to compile julia.

**Comment by cbecker** [comment]
Indeed, that's what archlinux has done. I fixed it by following your advice and applying the patch at https://projects.archlinux.org/svntogit/packages.git/tree/trunk/clang-3.7.0-add-gcc-abi-tag-support.patch?h=packages/llvm to the llvm source downloaded by Julia.

This is a bit of a nasty workaround but it worked fine. Thanks ;)

**Comment by smldis** [comment]
Hello, I am getting a similar error while trying to execute a c++ example from the gecode library (https://gist.github.com/smldis/e987ab9fa8340a4452ed6c2ab97541b9).

The error is: 
` LLVM ERROR: Program used external function '_ZN6Gecode3Int9IntVarImp12perform_copyERNS_5SpaceEb' which could not be resolved!`

I am on archlinux, julia v0.6-dev, and LLVM/clang 3.9.1. I also enabled and recompiled Cxx with RTTI.
Any suggestion? I am not an expert.

**Comment by Keno** [comment]
It can't find the symbols in the current process. You need to make sure to dlopen the library (see here: https://github.com/Keno/Cxx.jl#example-8-using-c-with-shared-libraries). If that still doesn't work, make sure the symbol is exported from the library.

**Comment by smldis** [comment]
Thank you, it was a dumb question.. My first C++ program thanks to Cxx. It's working great!
