### ISSUE TITLE
IJulia hangs on "using Cxx"

### ISSUE THREAD

**Issue by oschulz** [Keno/Cxx.jl#228]
When I use Cxx.jl with Julia 0.5, IJulia hangs on

    using Cxx

The cell is evaluated, and the usual warning (`deprecated syntax "call(F::Cxx.CppPtr [...]`, etc.) appear, just like on the Julia console, but evaluation of the cell never completes. I'm using 0.5.0-dev+2440 (Commit 2bb94d6, corresponds to last official nightly snapshot) on Ubuntu 14.04.

With Julia 0.4.3 (yes, I know Cxx.jl officially doesn't support 0.4 ;-) ), I can use Cxx.jl in IJulia without problems.

**Comment by Keno** [comment]
I'm currently in the prices of updating Cxx for the recent 0.5 changes. Hang on a few more days.

**Comment by oschulz** [comment]
No problem, thanks!

**Comment by Keno** [comment]
Updated to all the recent changes on master and passes all tests for me, but the paint is still wet ;).

**Comment by oschulz** [comment]
Nice, works fine in IJulia now, and all warnings are gone, too - thanks!
