### ISSUE TITLE
runtests.jl fails in 0.5.0-dev+2791

### ISSUE THREAD

**Issue by josefsachsconning** [Keno/Cxx.jl#231]
```
AWS-Sachs-Ubuntu$ usr/bin/julia ~/.julia/v0.5/Cxx/test/runtests.jl

WARNING: deprecated syntax "call(F::Cxx.CppPtr{Cxx.CxxQualType{Cxx.CppBaseType{:
_jl_function_t}, (false, false, false)}, (false, false, false)}, ...)".
Use "(F::Cxx.CppPtr{Cxx.CxxQualType{Cxx.CppBaseType{:_jl_function_t}, (false, fa
lse, false)}, (false, false, false)})(...)" instead.

WARNING: deprecated syntax "call(::Type{JLCppCast{T}}, ...)".
Use "(::Type{JLCppCast{T}})(...)" instead.
WARNING: Method definition (::Type{Cxx.CppDeref})(#T<:Any) in module Cxx at /home/sachs/.julia/v0.5/Cxx/src/codegen.jl:73 overwritten at /home/sachs/.julia/v0.5/Cxx/src/codegen.jl:75.
WARNING: Method definition (::Type{Cxx.CppAddr})(#T<:Any) in module Cxx at /home/sachs/.julia/v0.5/Cxx/src/codegen.jl:79 overwritten at /home/sachs/.julia/v0.5/Cxx/src/codegen.jl:81.
julia: /home/sachs/src/julia-master-with-cxx/src/debuginfo.cpp:1378: RTDyldMemoryManagerUnix::registerEHFrames(uint8_t*, uint64_t, size_t)::__lambda4: Assertion `(encoding & 0xf0) == 0x10 && "Only pcrel mode is supported"' failed.
zsh: abort (core dumped)  usr/bin/julia ~/.julia/v0.5/Cxx/test/runtests.jl
```

Here is my Make.user
```
#GCC >= 5 will not work
#override USECLANG=1
override LLVM_VER=3.7.1
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# For LLDB support also
override BUILD_LLDB=1
override LLDB_DISABLE_PYTHON=1
USE_GPL_LIBS=0
OPENBLAS_DYNAMIC_ARCH=1
JULIA_CPU_TARGET=core2
```

**Comment by Keno** [comment]
Yep, I know. I'm almost done updating for all the recent changes that have happened on master, but I'm not quite there yet.

**Comment by Keno** [comment]
Updated to all the recent changes on master and passes all tests for me, but the paint is still wet ;).

**Comment by josefsachsconning** [comment]
No more warnings, but I still get the failure.
```
AWS-Sachs-Ubuntu$ usr/bin/julia ~/.julia/v0.5/Cxx/test/runtests.jl
julia: /home/sachs/src/julia-master-with-cxx/src/debuginfo.cpp:1378: RTDyldMemoryManagerUnix::registerEHFrames(uint8_t*, uint64_t, size_t)::__lambda4: Assertion `(encoding & 0xf0) == 0x10 && "Only pcrel mode is supported"' failed.
zsh: abort (core dumped)  usr/bin/julia ~/.julia/v0.5/Cxx/test/runtests.jl```

**Comment by Keno** [comment]
Hmm, that actually looks like a bug in julia proper then. @yuyichao wrote that code, so I'll just ping him here and see if he wants to tackle that.

**Comment by yuyichao** [comment]
Could you check what is the value of `encoding` in the debugger?

**Comment by yuyichao** [comment]
And if possible dump the content of the ehframe (`dump memory <filename> Addr Addr + LoadAddr` in gdb should do it).

**Comment by josefsachsconning** [comment]
```
(gdb) p encoding
$1 = (DW_EH_PE &) @0x7fffffffb64f: 63
(gdb) dump memory dump_issue_231 Addr Addr + LoadAddr
/build/buildd/gdb-7.7.1/gdb/utils.c:1067: internal-error: virtual memory exhausted: can't allocate 140737347070744 bytes.
A problem internal to GDB has been detected,
further debugging may prove unreliable.```

**Comment by yuyichao** [comment]
Oooops, did I say `Addr + LoadAddr`......................................................... I meant `Addr + Size` ....... ;-p

**Comment by josefsachsconning** [comment]
[dump_issue_231.txt](https://github.com/Keno/Cxx.jl/files/142825/dump_issue_231.txt)

**Comment by yuyichao** [comment]
Thx. `0x3f` (63) isn't a valid encoding so it seems that the parsing of some fields before it was wrong.... I'll need to have a look at your dump file later.

**Comment by yuyichao** [comment]
A breakdown of the CIE (up to the point we care about):

* CIE Length (4 bytes) [0x20 0x00 0x00 0x00]: 32
* CIE ID (4 bytes) [0x00 0x00 0x00 0x00]: 0 (CIE)
* CIE version (1 byte) [0x01]: 1
* Augmentation string (NUL term) [0x7a 0x50 0x4c 0x52 0x00]: "zPLR"
* Code alignment factor (unsigned LEB128) [0x01]: 1
* Data alignment factor (signed LEB128) [0x78]: -8
* Return address register (1 byte for CIE version 1) [0x10]: 16
* Augmentation data:

    * ("z") Augmentation data length (unsigned LEB128) [0x0b]: 11
    * ("P") Personality data:

        * Encoding (1 byte) [0x9c]: `sdata8 | pcrel | indirect`
        * personality function (8 bytes)
          [0xe5 0x3f 0x04 0x00 0x00 0x00 0x00 0x00]:

    * ("L") LSDA encoding (1 byte) [0x1c]: `sdata8 | pcrel`
    * ("R") FDE encoding (1 byte) [0x1c]: `sdata8 | pcrel`

The issue is that I didn't skip the personality function (and only skipped the encoding....), will submit a PR soon.
