### ISSUE TITLE
Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by LMescheder** [Keno/Cxx.jl#241]
Running the tests for Cxx.jl on Ubuntu 14.04 under julia 0.5-dev results in the following error on my system:

``
julia:(path-to-julia-source)/src/jitlayers.cpp:376: JuliaOJIT::ModuleHandleT JuliaOJIT::addModule(std::unique_ptr<llvm::Module>): Assertion `F->isIntrinsic() || findUnmangledSymbol(F->getName()) || SectionMemoryManager::getSymbolAddressInProcess(F->getName())' failed.
``

Same things happen when I try to execute any c++ code in the terminal. Installation and testing of julia + installation of Cxx.jl did not raise any errors.

**Comment by Keno** [comment]
https://github.com/JuliaLang/julia/pull/15742
