### ISSUE TITLE
@cxxnew vs icxx"""..."""

### ISSUE THREAD

**Issue by schmrlng** [Keno/Cxx.jl#242]
Not really an issue, but I was wondering whether I should have a preference between using ```@cxxnew``` or ```icxx"""..."""```. Behind the scenes with types, the two options appear to have slightly different implementations, but they have the same basic behaviour:

```julia
julia> using Cxx

julia> cxx"""#include <iostream>
              class Hello
              {
                  public:
                      void hello_world(const char *now){
                          std::string snow = now;
                          std::cout << "Hello World! Now is " << snow << std::endl;
                      }
               };"""
true

julia> hello_class = @cxxnew Hello()

(class Hello *) @0x000000000ae43780

julia> typeof(hello_class)
Cxx.CppPtr{Cxx.CppValue{Cxx.CxxQualType{Cxx.CppBaseType{:Hello},(false,false,false)},N},(false,false,false)}

julia> @cxx hello_class->hello_world(pointer("asdasd"))
Hello World! Now is asdasd

julia> hello_class2 = icxx"Hello* h = new Hello(); h;"

(class Hello *) @0x0000000004db16c0

julia> typeof(hello_class2)
Cxx.CppPtr{Cxx.CxxQualType{Cxx.CppBaseType{:Hello},(false,false,false)},(false,false,false)}

julia> @cxx hello_class2->hello_world(pointer("asdasd"))
Hello World! Now is asdasd
```

**Comment by Keno** [comment]
Generally I use `icxx` nowadays. `@cxxnew` is legacy and may be removed in the future.

**Comment by ScottPJones** [comment]
Isn't it the case that within the string macro, you can use real C++ syntax, but you are limited by the way macros work (things have to be parseable as Julia) with `@cxx`?

**Comment by Keno** [comment]
Yes, `@cxx` and friends pun on julia syntax with somewhat ill defined semantics. `icxx` uses complete C++ syntax with a more well defined translation between julia and C++ types.
