### ISSUE TITLE
Issue while wrapping ArrayFire

### ISSUE THREAD

**Issue by ranjanan** [Keno/Cxx.jl#243]
The title could have been more informative, but I really didn't know what to call it.

While doing 
```julia
let body = i->(a[i]=b[i]+c[i]; nothing;)
       icxx"""
           gfor (af::seq $i, 10) $body($i);
       """ 
end
```

I get the error 
ERROR: MethodError: no method matching _getindex(::ArrayFire.AFArray{Float32,1}, ::Cxx.CppPtr{Cxx.CppRef{Cxx.CppBaseType{symbol("af::seq")},(false,false,false)},(false,false,false)})` even though I have 
```julia
_getindex(a::AFArray, i::vcpp"af::seq") 
``` 
defined

**Comment by Keno** [comment]
The underlying bug is fixed. You'll still have to define, `_getindex(a::AFArray, i::rcpp"af::seq")` or even better a general `_getindex(a::AFArray, i) = icxx"$a[$i];"`.
