### ISSUE TITLE
Compiler error that doesn't actually seem like an error

### ISSUE THREAD

**Issue by JonathanAnderson** [Keno/Cxx.jl#245]
So I have a custom date class like the following

    #include <cstdint>
    namespace foobar
    {

    class Date
    {
    public:
        explicit constexpr Date(int16_t yyyy, int8_t mm, int8_t dd);
        constexpr bool operator==(Date rhs) const;
    private:
        int16_t _yyyy = 0;
        int8_t  _mm = 0;
        int8_t  _dd = 0;
    };

    constexpr Date::Date(int16_t yyyy, int8_t mm, int8_t dd)
     :  _yyyy(yyyy)
     ,  _mm(mm)
     ,  _dd(dd)
    { }

    constexpr bool Date::operator==(Date rhs) const
    {
        return (_dd == rhs._dd) and (_mm == rhs._mm) and (_yyyy == rhs._yyyy);
    }
  
    }

And with a fresh julia build (`Commit 1b4618e* (0 days old master)`) and after freshly cloning and building `Cxx.jl.git` this morning. I get the following error when including the following 

    julia> using Cxx

    julia> addHeaderDir("/mypath/source", kind=C_User);

    julia> Libdl.dlopen("/mypath/lib/libtime.so", Libdl.RTLD_GLOBAL);

    C++ > #include "time/date/Date.H"
    In file included from :1:
    In file included from REPL:1:
    /mypath/source/time/date/Date.H:24:32: error: expected ';' after return statement
            return (_dd == rhs._dd) and (_mm == rhs._mm) and (_yyyy == rhs._yyyy);
                                   ^
                                   ;
    true

This is strange, at this point I was wondering what was going on. But I figured I would try to use this class and it worked just fine...

    C++ > auto date1 = foobar::Date(2015,11,01);

    C++ > auto date2 = foobar::Date(2015,11,02);

    C++ > date1 == date1
    true

    C++ > date1 == date2
    false

Is there anyway I can find more debug information or further dig into what is going on here?

**Comment by JonathanAnderson** [comment]
I'm also running into errors like the following which look very similar to the above.

```julia
C++ > #include <memory>
true

C++ > auto up = std::make_unique<int>(42);
REPL:1:11: error: no template named 'make_unique' in namespace 'std'; did you mean 'llvm::make_unique'?
auto up = std::make_unique<int>(42)
          ^~~~~~~~~~~~~~~~
          llvm::make_unique
/juliapath/usr/bin/../include/llvm/ADT/STLExtras.h:354:1: note: 'llvm::make_unique' declared here
make_unique(Args &&... args) {
^
In file included from :1:
REPL:1:11: error: no template named 'make_unique' in namespace 'std'; did you mean 'llvm::make_unique'?
auto up = std::make_unique<int>(42)
          ^~~~~~~~~~~~~~~~
          llvm::make_unique
/juliapath/usr/bin/../include/llvm/ADT/STLExtras.h:354:1: note: 'llvm::make_unique' declared here
make_unique(Args &&... args) {
^

C++ > std::cout << (*up) << std::endl;
42
```

**Comment by Keno** [comment]
The first issue was that keyword operators such as `and` were disallowed by default. I have changed that to allow them. For the second issue, I suspect your standard C++ library is not C++14 compliant and does not in fact have make_unique. LLVM helpfully defines this function for you and clang autocorrected the name space. There is some argument to be made that we shouldn't allow clang autocorrect to happen, but I've actually found it quite convenient in interactive mode, since it'll plaster over simple syntax errors like forgotten semicolons.

**Comment by JonathanAnderson** [comment]
Thanks Keno. You're right re the non standard library. We are apparently using a `chroot` for our builds to point at the correct build tree. Is there any way I can point the compiler to a custom path for the c++ library?

I like the llvm autocorrect as it has corrected misspelled namespaces for me as well and a plethora of forgotten semicolons.

**Comment by Keno** [comment]
No, that is currently not possible. The code that does standard library detection is here: https://github.com/Keno/Cxx.jl/blob/master/src/initialization.jl. I think it would be reasonable to have an environment variable to control the default chroot, as we do for julia home (https://github.com/Keno/Cxx.jl/blob/master/deps/build.jl#L16). A hackier alternative is to create a new compiler instance for the proper chroot and use that one instead.
