### ISSUE TITLE
Interpolating literals into template class constructors

### ISSUE THREAD

**Issue by KristofferC** [Keno/Cxx.jl#246]
Hi, I am playing around with calling the Eigen linalg library: http://eigen.tuxfamily.org/

Creating a fixed size matrix templated on the element type and rows + columns using `icxx` work fine.
```jl
julia> using Cxx

julia> cxx"""#include "/home/kristoffer/Downloads/eigen-eigen-07105f7124f9/Eigen/Core" """

julia> mat = icxx"Eigen::Matrix<double, 4, 4>();"
(class Eigen::Matrix<double, 4, 4, 0, 4, 4>) {
}
```

Also, interpolating the element type into the `icxx` string works:
```jl
julia> T = Cfloat;

# Interpolating the type into icxx string OK
julia> mat = icxx"Eigen::Matrix<$T, 4, 4>();"
(class Eigen::Matrix<float, 4, 4, 0, 4, 4>) {
}
```

However, interpolating the rows or columns does not:

```jl
julia> rows = 4

julia> mat = icxx"Eigen::Matrix<$T, $rows, 4>();"
In file included from :1:
:2:29: error: non-type template argument is not a constant expression
Eigen::Matrix<__juliatype1, __juliavar2, 4>();
                            ^~~~~~~~~~~
:2:29: note: read of non-const variable '__juliavar2' is not allowed in a constant expression
:1:1: note: declared here
```

I realize that this is because only types are swapped out to be `__juliatype` in the `icxx` macro and the rest gets passed as non constant `__juliavar`s. Is there any way to wrap the literal or something to make interpolating the rows and columns work?

Thanks!

**Comment by KristofferC** [comment]
I found this test: https://github.com/Keno/Cxx.jl/blob/70f4c5463d346184d35f7f9151b688cf8aad8a31/test/misc.jl#L85

so curly braces seem like it should work, it however only seem to work with bools

Templated on bool curly braces work:
```jl
cxx"""
template < bool T > class baz {
public:
    baz() {};
};
"""

@cxxnew baz{false}::baz()
(class baz<false> *) @0x000000000d052ce0
```

Templated on int, curly bracer errors:
```jl
cxx"""
template < int T > class bazint {
public:
    bazint() {};
};
"""

@cxxnew bazint{1}::bazint()
ERROR: Invalid NNS 1
 in eval(::Module, ::Any) at ./boot.jl:237
```

**Comment by Keno** [comment]
Making this work as is would significantly pessimize all other code. However, I've implemented something that should work just fine. Regular warnings regarding overspecialization apply:
```
julia> rows = Val{4}

julia> mat = icxx"Eigen::Matrix<$T, $rows, 4>();"
```

**Comment by KristofferC** [comment]
Thanks for the help. This however broke what previously used to work (interpolating datatypes):

```jl
julia> T = Cfloat;

julia> mat = icxx"Eigen::Matrix<$T, 4, 4>();"
ERROR: Don't know how to make this a C++ constant
 [inlined code] from /home/kristoffer/.julia/v0.5/Cxx/src/cxxstr.jl:234
```

The problem seems to be that this check: https://github.com/Keno/Cxx.jl/blob/1c6819a5af95090282ba1016a5561ba537d22adc/src/cxxstr.jl#L301 fails and the path which tries to emit a const is taken instead of the type path.

`T` here is an instance of a `QualType` so not a `Type`, no? Changing `Type -> QualType` makes everything work for my application but maybe it is not correct in other cases.

**Comment by Keno** [comment]
Yes you're correct. Sorry, I can't currently run the tests locally, so I didn't catch this.

**Comment by Keno** [comment]
5a84bdf32c25ff0371c505997a6b72e1b7507a9c

**Comment by KristofferC** [comment]
Thanks again!
