### ISSUE TITLE
Turn on support for #pragma once

### ISSUE THREAD

**Issue by JonathanAnderson** [Keno/Cxx.jl#251]
I am using a library that only uses the `#pragma once` include directive for header guards and ran into a bunch of redefinition errors. I've verified that manually adding include guards to the library fixes the problem but this may occur in the future again.

I've been looking through the llvm documentation to see if there was an option i could toggle in `bootstrap.cpp` al la `Cxx->CI->getSpecialOpts().TurnOnPragmaOnce = 1;` but I haven't found anything.
These were the closest links i've found dealing with the option.

* http://clang.llvm.org/doxygen/classclang_1_1PreprocessorOptions.html
* http://clang.llvm.org/doxygen/classclang_1_1Preprocessor.html#a79c836c269d26280f300a82824cde7b4

Since I don't know what to do next, I figured I would ask for help. Meanwhile I will continue to see if I can figure this out.

**Comment by Keno** [comment]
Pragma once should always be active, so it may instead be a problem with the way we generate file names (i.e. clang may not realize that two includes point to the same file).

**Comment by JonathanAnderson** [comment]
The more I think about the behaviors of how `cxxinclude` works I believe it may be reasonable.

Lets create the following two files.

/tmp/test_1.hpp
```
#pragma once
struct A1 { int x = 1; };
```

/tmp/test_2.hpp
```
#pragma once
#include "/tmp/test_1.hpp"
struct A2 { int x = 2; };
```

And then include them and include the second one again...
```
julia> cxxinclude("/tmp/test_1.hpp")

julia> cxxinclude("/tmp/test_2.hpp")

julia> cxxinclude("/tmp/test_2.hpp")
In file included from :1:
/tmp/test_2.hpp:3:8: error: redefinition of 'A2'
struct A2 { int x = 2; };
       ^
/tmp/test_2.hpp:3:8: note: previous definition is here
struct A2 { int x = 2; };
```

It reloads the definition from the file I told it to include and it respects the pragma in `test_1.hpp`. This is reasonable behavior if I was editing `test_2.hpp` and wanted it re-included.

The frustrating case is when you include `test_2.hpp` and then include `test_1.hpp`

```
julia> cxxinclude("/tmp/test_2.hpp")

julia> cxxinclude("/tmp/test_1.hpp")
In file included from :1:
/tmp/test_1.hpp:2:8: error: redefinition of 'A1'
struct A1 { int x = 1; };
       ^
/tmp/test_1.hpp:2:8: note: previous definition is here
struct A1 { int x = 1; };
```

Here I just didn't know that `test_1.hpp` has been included as a result my including `test_2.hpp`

However, using the `cxx""" ... """` syntax to include these files seems to respect all the pragmas.

```
julia> cxx""" #include "/tmp/test_1.hpp" """
true

julia> cxx""" #include "/tmp/test_2.hpp" """
true

julia> cxx""" #include "/tmp/test_2.hpp" """
true

```

Also if I define `/tmp/test_3.hpp` without the pragma
```
#include "/tmp/test_2.hpp"
struct A3 { int x = 3; };
```

And I `cxx""" ... """` include the file twice, this correctly throws errors.

```
julia> cxx""" #include "/tmp/test_3.hpp" """
true

julia> cxx""" #include "/tmp/test_3.hpp" """
In file included from :1:
In file included from __cxxjl_18.cpp:1:
/tmp/test_3.hpp:2:8: error: redefinition of 'A3'
struct A3 { int x = 3; };
       ^
/tmp/test_3.hpp:2:8: note: previous definition is here
struct A3 { int x = 3; };
       ^
true
```

So since I think this is working in a reasonable way, I'm going to close this.

Thanks.

**Comment by iamed2** [comment]
It would be nice if this was supported such that I can use `cxxinclude` instead of doing:
```julia
eval(Cxx.process_cxx_string("#include <$header>", true, false))
```
