### ISSUE TITLE
Setting member variables

### ISSUE THREAD

**Issue by lumenosys** [Keno/Cxx.jl#255]
Hi,

I stumbled across Cxx and so far I am VERY impressed. This is a very nice piece of work.

I could have missed it, but I can't seem to figure out how to assign values to member variables in a C++ object. For example it would be very nice to do this:

 obj = @cxxnew myclass()
@cxx obj->member = 1

I know I can do it with a setter function, or a wrapper like this:

Void set_member(myclass *obj, int val)
{
  obj->member = val;
}

But in my case I am using a third party c++ library and I would like to avoid creating wrappers for all public member variables.

So is this possible? Are there any plans to implement this if not currently supported?

Thanks for the great work!

Regards, Devin

**Comment by Keno** [comment]
Try the string macros:
```
icxx"$obj->member = 1;"
```

**Comment by lumenosys** [comment]
Yep, that works. Is there a significant performance penalty for doing this vs. calling a setter function?

**Comment by Keno** [comment]
Nope, performance is the same. It gets at the IR level.

**Comment by lumenosys** [comment]
Awesome. Thanks!
