### ISSUE TITLE
LoadError while using Cxx on Mac OS X

### ISSUE THREAD

**Issue by ashwincarvalho** [Keno/Cxx.jl#262]
I followed the instructions to install Julia v0.5-dev with the following `Make.user` file:
```
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
```

I get the following error when I call `using Cxx`:

```
ERROR: LoadError: UndefVarError: svec not defined
 in include_from_node1(::String) at ./loading.jl:426
 in eval(::Module, ::Any) at ./boot.jl:231
 in require(::Symbol) at ./loading.jl:357
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
while loading /Users/Ty/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 147
```

I'm not sure if it's an issue with my Julia installation. My build passes all tests.

**Comment by Keno** [comment]
What commit is julia on?

**Comment by ashwincarvalho** [comment]
02ac2b10bf4ad355aa23f7147a950e166ee1cd79

**Comment by ashwincarvalho** [comment]
[02ac2b1](https://github.com/JuliaLang/julia/commit/02ac2b10bf4ad355aa23f7147a950e166ee1cd79)

**Comment by ashwincarvalho** [comment]
This is not an issue on an older [commit](https://github.com/JuliaLang/julia/commit/92c86375a3fbb7f4369537b0c0fac09f3d58720e) (chosen at random).

**Comment by Keno** [comment]
96c285ddef2b7d50715d8db9b318ca5a0251e92a
