### ISSUE TITLE
Bulid libcxxabi with compiler-rt

### ISSUE THREAD

**Issue by vchuravy** [Keno/Cxx.jl#277]
I just run into the issue that Clang for Cxx.jl was picking up the wrong libc (at least I think that was the issue) and I was able to solve it by compiling libcxxabi against compiler-rt.
This is supported since LLVM 3.9 and requires activating `-DLIBCXXABI_USE_COMPILER_RT=ON` in llvm.mk.

X-Ref: https://reviews.llvm.org/rL275505

@Keno I have a patch for the Julia build system, but since I am running on a non-standard system (on a cluster) I don't know if this change would be generally appropriate.

**Comment by Keno** [comment]
Should be a Makefile option one can set in Make.user.

**Comment by vchuravy** [comment]
I thought I got around it put apparently I tested the wrong thins: So the error I am seeing is:

```
In file included from /home/v/valentin-churavy/src/julia-gpu/usr/bin/../lib/clang/3.9.0/include/__clang_cuda_runtime_wrapper.h:51:
/apps/free/gcc/4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/../../../../include/c++/4.8.4/cstdlib:126:11: error: no member named 'at_quick_exit' in the global namespace
  using ::at_quick_exit;
        ~~^
/apps/free/gcc/4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/../../../../include/c++/4.8.4/cstdlib:149:11: error: no member named 'quick_exit' in the global namespace
  using ::quick_exit;
        ~~^
In file included from :1:
```

**Comment by Keno** [comment]
If you're using libc++ you need to make sure not to pick up libstdc++ as well.

**Comment by vchuravy** [comment]
NVM, it was a weird configuration bug on my side
