### ISSUE TITLE
symbol lookup error _ZN4llvm3sys16getProcessTripleEv

### ISSUE THREAD

**Issue by jw3126** [Keno/Cxx.jl#284]
I followed the installation instructions and building julia+Cxx apparently worked. Now if I try to use Cxx I get the following:
```
julia> using Cxx
julia: symbol lookup error: /home/admin/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so: undefined symbol: _ZN4llvm3sys16getProcessTripleEv
```
Julia Version 0.6.0-dev.8
Commit 043eb26* (2016-08-04 12:29 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

**Comment by vchuravy** [comment]
x-ref: https://github.com/Keno/Cxx.jl/issues/271#issuecomment-235917608

**Comment by Keno** [comment]
I've added ABI auto-detection. I believe this should be fixed.

**Comment by ink1** [comment]
I have the same error again.
OS: CentOS 7 (3.10.0-123.20.1.el7.x86_64) 
Julia: 0.6.1, 0.6.2 general Linux build
Cxx build downloads and installs cfe-3.9.1.src.tar.xz and llvm-3.9.1.src.tar.xz
```
julia> using Cxx
INFO: Precompiling module Cxx.
ERROR: LoadError: LoadError: could not load library "/home/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi"
/home/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so: undefined symbol: _ZTVN4llvm2cl12basic_parserISsEE
Stacktrace:
 [1] dlopen(::String, ::UInt32) at ./libdl.jl:97
 [2] init_libcxxffi() at /home/.julia/v0.6/Cxx/src/initialization.jl:20
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/.julia/v0.6/Cxx/src/initialization.jl, in expression starting on line 22
while loading /home/.julia/v0.6/Cxx/src/Cxx.jl, in expression starting on line 163
ERROR: Failed to precompile Cxx to /home/.julia/lib/v0.6/Cxx.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
```

**Comment by ink1** [comment]
The build itself is fine though.

**Comment by ink1** [comment]
@Keno sorry, should i open another issue?

**Comment by ink1** [comment]
In case anyone else hits this problem, it seems to be related to the compiler - the default gcc 4.8.5 on CentOS is not sufficient. I used gcc 7.2 (which I built with compatible ABI support) and it worked.
