### ISSUE TITLE
Passing references as arguments?

### ISSUE THREAD

**Issue by izaid** [Keno/Cxx.jl#290]
Very impressed with Cxx.jl so far, thanks for creating and maintaining it. I've been doing some wrapping of a preexisting C++ library, and it seems there is a bug (or I'm misunderstanding) with how references should be handled.

For instance, how do I get the following simple example to work? It should simply set the value of `res` in Julia to 7. Currently, that value does not get set and `0` is printed instead.

```
using Cxx

cxx"""
    void func(int &res) {
        res = 7;
    }
    """

res = Cint(0)

@cxx func(res)
println(res)
```

**Comment by vchuravy** [comment]
This works:
```julia
f(x::Ref{Cint}) = icxx"""
  $x = 7;
""""
res = Ref{Cint}(0)
f(res)
@assert res[] == 7
```

The icxx macro in general is really nice.

**Comment by izaid** [comment]
Okay, thanks! However, the only thing is that I'm not actually writing the C++ source -- it's an external library, the stuff in the cxx string I just gave as an example.

Should `res = Ref{Cint}(0); f(res)` work if `f` is a simple external function with a Cint passed by reference? I'm finding that it doesn't -- I get a bad type information error.

**Comment by Keno** [comment]
The `@cxx` macro is generally deprecated (I should probably add a deprecation message to that extent). Using `icxx`, `Ref` should be generally converted to C++ references.

**Comment by izaid** [comment]
@Keno Thanks, the combination of `icxx` and declaring `Ref{T}` worked perfectly. So, to be clear, should I not be using `@cxx` any more at all? icxx is fine, but it kind of sucks putting all my C++ code in strings.

**Comment by Keno** [comment]
Yes, that's kind of the reason I haven't deprecated it yet. The problem with punning on syntax like that though is that it'll never match watch C++ does and can thus give surprising behavior. I can certainly fix it to handle this case, but I'm not convinced I should keep encouraging it's usage. Maybe only allow the simple function call syntax and forbid the more questionable syntax punning.

**Comment by izaid** [comment]
So, for what it's worth, I'm using Cxx.jl to interface with some complex hardware with a C++ API. I was (surprisingly) literally able to do everything with `@cxx` except for this reference issue. I was really impressed that it just worked out of the box, in comparison something like Cython (which is also great) would have required more work.

**Comment by Keno** [comment]
I've decided to give `@cxx` a stay of execution and added a fix for the type error you saw.

**Comment by izaid** [comment]
@Keno Just want to throw in my 0.02 now that I've used Cxx.jl pretty extensively. I agree with you, `@cxx` should go, the type-punning will never work fully. `cxx"..."` and `icxx"..."` should be used instead, but all the docs would have to be updated to reflect this.

**Comment by fasiha** [comment]
Question. How would @vchuravy’s example work with `std::complex<double>`?

A simple-minded approach fails:
```julia
julia> y = 0.0im
0.0 + 0.0im

julia> res = Ref(y)
Base.RefValue{Complex{Float64}}(0.0 + 0.0im)

julia> icxx"$res = std::complex<double>(12.0,13.0);"
:2:13: error: no viable overloaded '='
__juliavar1 = std::complex<double>(12.0,13.0);
~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:2:13: note: type '(anonymous class)' is incomplete
__juliavar1 = std::complex<double>(12.0,13.0);
~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: A failure occured while parsing the function body
```

**Comment by Keno** [comment]
There'd have to be appropriate logic in Cxx.jl to map Julia's `Complex` type to `std::complex`, which there isn't right now. I can take a look at that in the morning.

**Comment by fasiha** [comment]
Thanks @Keno! Sorry for persisting in off-topic, but do you have any tips for doing this kind of thing with Julia vector/arrays? I’d like to do something like—and this is a super-wild guess:
```julia
arr = [1.0; 1.1; 1.2]
icxx""" std::cout << ($arr)[0] << std::endl; """
```
but of course that doesn’t work, and I’m not familiar enough with Julia `RefArray`s to understand how to get this to work. (My end goal is to be able to represent Julia vectors/arrays as C++ containers and pass them to functions in a library, etc.). Thanks!
