### ISSUE TITLE
Cxx build fails on Windows

### ISSUE THREAD

**Issue by Gnimuc** [Keno/Cxx.jl#293]
Currently, `libLLVM-3.7.1` is not shipped with Julia-0.5 binaries on windows, only `LLVM-3.7.dll` there.

```
INFO: Building Cxx
writing path.jl file
Tuning for julia installation at C:\Users\qyp\AppData\Local\Julia-0.5.0\bin wit
 sources possibly at C:\Users\qyp\AppData\Local\Julia-0.5.0\bin\../..
=================================[ ERROR: Cxx ]================================


LoadError: could not load library "libLLVM-3.7.1"
The specified module could not be found.

while loading C:\Users\qyp\.julia\v0.5\Cxx\deps\build.jl, in expression startin
 on line 26

===============================================================================


================================[ BUILD ERRORS ]===============================


WARNING: Cxx had build errors.

 - packages with build errors remain installed in C:\Users\qyp\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

===============================================================================
```

I've tried to manually set up [this line](https://github.com/Keno/Cxx.jl/blob/54da762a63798a055087a7242e5b49444a8f4cb5/deps/build.jl#L26) to `LLVM-3.7`, but another error jumps out:(**UPDATE**: this is actually expected, because Windows doesn't have `make`,  the correct way is to build this package in `cygwin` or `msys2`.)

```
INFO: Building Cxx
writing path.jl file
Tuning for julia installation at C:\Users\qyp\AppData\Local\Julia-0.5.0\bin with
 sources possibly at C:\Users\qyp\AppData\Local\Julia-0.5.0\bin\../..
INFO: Building julia binary build
=================================[ ERROR: Cxx ]=================================


LoadError: could not spawn `make -j24 -f BuildBootstrap.Makefile 'BASE_JULIA_BIN
=C:\Users\qyp\AppData\Local\Julia-0.5.0\bin' 'BASE_JULIA_SRC=C:\Users\qyp\AppDat
a\Local\Julia-0.5.0\bin\../..'`: no such file or directory (ENOENT)
while loading C:\Users\qyp\.julia\v0.5\Cxx\deps\build.jl, in expression starting
 on line 41

================================================================================


================================[ BUILD ERRORS ]================================


WARNING: Cxx had build errors.

 - packages with build errors remain installed in C:\Users\qyp\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

================================================================================


```

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

julia> Pkg.status()
1 required packages:
 - Cxx                           0.0.1+             master (dirty)
```

**Comment by rand5** [comment]
+1

**Comment by samuelpowell** [comment]
Is there a known fix for this problem?

**Comment by musm** [comment]
also interested in windows support, doesn't 0.6 ship with llvmlib 3.9?

**Comment by Gnimuc** [comment]
I just attempted to cross-compile the package with julia-master in Cygwin, but with no luck, compilation failed on [87%](https://gist.github.com/Gnimuc/40423b54877737fd7c2bb674b15b6797), I don't have any idea on how to fix this.

**Comment by musm** [comment]
Any updates for windows support?

**Comment by Keno** [comment]
The problem on windows is that I don't really know what to do about the standard library. Both linux and mac have one installed usually, but Windows generally doesn't. I suppose the right answer is to ship the mingw headers, but setting up a functional mingw environment is quite a step up from just shipping the binary.

**Comment by ihnorton** [comment]
Requiring to install ming doesn't seem too extreme for a developer tool.

(by the way, apparently clang windows support is now sufficiently advanced to [compile Qt (and pass tests?!?)](http://doc.qt.io/qt-5/windows-requirements.html#clang-clang-cl) in MSVC mode)

**Comment by phlavenk** [comment]
For me, even cxx would need to download full cygwin directory, having this handled by Pkg would be a great solution. The dream of course would be the possibility co compile the whole Julia-llvm-clang-cxx by the Clang-MSVC... But of course, this is not the priority for the majority of Julia developers working on unix-like systems.

**Comment by DrKrar** [comment]
it's just a great Package, I look forward to seeing it working in windows in the latest Julia soon.

**Comment by DrKrar** [comment]
using Cxx
did not scuceeded with the Error:

ERROR: LoadError: LoadError: could not open file E:\Users\DrKra.julia\v0.7\Cxx\src../deps/build/clang_constants.jl
Stacktrace:
[1] include_relative(::Module, ::String) at .\loading.jl:464
[2] include at .\sysimg.jl:14 [inlined]
[3] include(::String) at E:\Users\DrKra.julia\v0.7\Cxx\src\Cxx.jl:142
[4] include_relative(::Module, ::String) at .\loading.jl:464
[5] include at .\sysimg.jl:14 [inlined]
[6] include(::String) at E:\Users\DrKra.julia\v0.7\Cxx\src\Cxx.jl:142
[7] include_relative(::Module, ::String) at .\loading.jl:464
[8] include(::Module, ::String) at .\sysimg.jl:14
[9] anonymous at .<missing>:2
while loading E:\Users\DrKra.julia\v0.7\Cxx\src\typetranslation.jl, in expression starting on line 434
while loading E:\Users\DrKra.julia\v0.7\Cxx\src\Cxx.jl, in expression starting on line 162

**Comment by DrKrar** [comment]
it still not working in the latest julia version 1.1.0-DEV.280 (2018-09-18)
```
julia> using Cxx
[ Info: Precompiling Cxx [a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2]
ERROR: LoadError: path.jl not generated. Try running Pkg.build("Cxx")
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at none:0
 [3] include at .\boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1041
 [5] include(::Module, ::String) at .\sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:319 [inlined]
 [8] eval(::Expr) at .\client.jl:389
 [9] top-level scope at .\none:3
in expression starting at C:\Users\Mohamed\.julia\packages\Cxx\E2Qs\src\Cxx.jl:144
ERROR: Failed to precompile Cxx [a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2] to C:\Users\Mohamed\.julia\compiled\v1.1\Cxx\ESGkI.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1187
 [4] _require(::Base.PkgId) at .\logging.jl:311
 [5] require(::Base.PkgId) at .\loading.jl:855
 [6] macro expansion at .\logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at .\loading.jl:837
```

**Comment by Gnimuc** [comment]
hi, @DrKrar, this package needs an overhaul for being compatible with Julia 1.0(LLVM6.0) which I guess won't happen in the near future. As for Windows support, we need to wait for LLVMBuilder to become more mature.

**Comment by Gnimuc** [comment]
I'm going to close this issue in favor of https://github.com/Keno/Cxx.jl/issues/390

**Comment by KronosTheLate** [comment]
Just a pointer to others - #390 is closed, and it is not windows specific. https://github.com/JuliaInterop/Cxx.jl/issues/366 is still open, so more similar to this issue.
