### ISSUE TITLE
How to dereference? syntax: "*" is not a unary operator

### ISSUE THREAD

**Issue by iamed2** [Keno/Cxx.jl#299]
I'm trying to dereference an argument to a function but I get this:

```
julia> @cxx Aws::InitAPI(*o)
syntax: "*" is not a unary operator
```

How can I dereference a pointer?

**Comment by Keno** [comment]
I'd recommend trying `icxx`: `icxx"Aws::InitAPI(*$o);"`

**Comment by iamed2** [comment]
Ah, okay, that works. 

The other way is noted here: https://github.com/Keno/Cxx.jl/blob/master/src/Cxx.jl#L22
