### ISSUE TITLE
AssertionError with type arguments

### ISSUE THREAD

**Issue by iamed2** [Keno/Cxx.jl#303]
This works:
```
julia> cxx"""std::shared_ptr<Aws::StringStream> foo = Aws::MakeShared<Aws::StringStream>("JULIA", "foo");"""
true
```
But this doesn't:
```
julia> @cxx Aws::MakeShared{Aws::StringStream}("JULIA", "foo")
AssertionError: isa(targs,Type)
```
In the latter case, `targs = Any[:(Aws::StringStream)]`.

**Comment by Keno** [comment]
Fixed, but the string macros still are the preferred way to do this. The syntax punning is very fragile.

**Comment by iamed2** [comment]
I think at some point I got `cxx` and `icxx` confused and thought that `icxx` couldn't return anything (and there's no examples showing that). I'll try `icxx` more often now I guess. But I still like the macro syntax as you don't have to use `$(...)` to interpolate.

**Comment by Keno** [comment]
> But I still like the macro syntax as you don't have to use $(...) to interpolate.

Yeah, that's why it's still around.
