### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [Keno/Cxx.jl#314]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/Keno/Cxx.jl/blob/0ad2a18eb926e85aa13bb7f7d77e2095ff12aef7/deps/build.jl#L29

**Comment by Keno** [comment]
This was done.
