### ISSUE TITLE
import Cxx but not using Cxx

### ISSUE THREAD

**Issue by jw3126** [Keno/Cxx.jl#316]
It seems that it is not possible to import Cxx, without using its namespace. E.g.
```
julia> import Cxx

julia> Cxx.@cxx_str("#include <iostream>")
ERROR: UndefVarError: @pcpp_str not defined

julia> Cxx.@icxx_str("""std::cout << "hi" << std::endl;""")
ERROR: UndefVarError: __current_compiler__ not defined
```
while 
```
julia> using Cxx

julia> Cxx.@cxx_str("#include <iostream>")
true

julia> Cxx.@icxx_str("""std::cout << "hi" << std::endl;""")
hi
(class std::basic_ostream<char> &) {
}
```
works fine.

**Comment by Keno** [comment]
Cxx uses `__current_compiler__` in the current scope to determine compiler instance. This is to allow you to switch the compiler instance using, e.g. `let __current_compiler__ = ...`. You'll have to manually set `__current_compiler__ = Cxx.Cxx.__default_compiler__` if you don't do `using Cxx`.

**Comment by jw3126** [comment]
Thanks for the fast answer! Julia still complains about `@pcpp_str`:
```
julia> import Cxx

julia> __current_compiler__ = Cxx.Cxx.__default_compiler__
Cxx.CxxInstance{1}()

julia> Cxx.@cxx_str("#include <iostream>")
ERROR: UndefVarError: @pcpp_str not defined
```

**Comment by Keno** [comment]
Fair enough. I should probably fix it to qualify `Cxx.@pcpp_str`.

**Comment by jw3126** [comment]
Am I correct that this is more or less `search and replace` and does not require understanding of the inner workings of `Cxx.jl`? If so I could do that for you.

**Comment by Keno** [comment]
I think the only problem is this one: https://github.com/Keno/Cxx.jl/blob/a681d006bfe97ec6490ee9c1920b14c147b515fe/src/cxxstr.jl#L658. If you want to try fixing that and submitting a PR that would be appreciated. Otherwise, I'll take a closer look at some point.

**Comment by jw3126** [comment]
Okay, I will try to fix it.
