### ISSUE TITLE
Pkg.build() failure

### ISSUE THREAD

**Issue by MohamedTaher** [Keno/Cxx.jl#319]
julia> Pkg.build("Cxx")
INFO: Building Cxx
writing path.jl file
Tuning for julia installation at /home/taher/GP_Project/julia/julia/usr/bin with sources possibly at /home/taher/GP_Project/julia/julia/usr/bin/../..
=================================================================[ ERROR: Cxx ]==================================================================

LoadError: type String has no field data
Use `Vector{UInt8}(str)` instead.
while loading /home/taher/.julia/v0.6/Cxx/deps/build.jl, in expression starting on line 29

=================================================================================================================================================

================================================================[ BUILD ERRORS ]=================================================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /home/taher/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

=================================================================================================================================================

**Comment by waltsims** [comment]
@MohamedTaher  I am also having the same issue. as mentioned in: #323

**Comment by waltsims** [comment]
it seems this issue should have been resolved by 54da9e141688d66c14e6de88916ba8aedf938e19 ?

**Comment by Keno** [comment]
I tagged v0.1.0, which has those commits.
