### ISSUE TITLE
Custom include path

### ISSUE THREAD

**Issue by cbecker** [Keno/Cxx.jl#326]
I find Cxx.jl very useful. Is there a 'politically-correct' way of setting the include path used by Cxx? It would be useful to use header-only libraries.

**Comment by vchuravy** [comment]
In CUDAnativelib I am setting the search path with: https://github.com/JuliaGPU/CUDAnativelib.jl/blob/bb3e67f41d29324fbc1200413fddaad33024f2ba/src/codegen.jl#L13-L15 and https://github.com/JuliaGPU/CUDAnativelib.jl/blob/bb3e67f41d29324fbc1200413fddaad33024f2ba/src/codegen.jl#L26. The second one should be the canonical correct one and the first one is needed if you want to prepend a path to Clang CPATH.

**Comment by cbecker** [comment]
Thank you, that worked!
