### ISSUE TITLE
 Precompiling fail on Julia 0.7-Dev

### ISSUE THREAD

**Issue by DrKrar** [Keno/Cxx.jl#355]
julia> using Cxx
INFO: Precompiling module Cxx.
ERROR: LoadError: LoadError: syntax: invalid escape sequence
Stacktrace:
 [1] include_relative(::Module, ::String) at .\loading.jl:464
 [2] include at .\sysimg.jl:14 [inlined]
 [3] include(::String) at E:\Users\DrKra\.julia\v0.7\Cxx\src\Cxx.jl:142
 [4] include_relative(::Module, ::String) at .\loading.jl:464
 [5] include(::Module, ::String) at .\sysimg.jl:14
 [6] anonymous at .\<missing>:2
while loading E:\Users\DrKra\.julia\v0.7\Cxx\src\../deps/path.jl, in expression starting on line 1
while loading E:\Users\DrKra\.julia\v0.7\Cxx\src\Cxx.jl, in expression starting on line 145
ERROR: Failed to precompile Cxx to E:\Users\DrKra\.julia\lib\v0.7\Cxx.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:598
 [2] _require(::Symbol) at .\loading.jl:407
 [3] require(::Symbol) at .\loading.jl:318

**Comment by DrKrar** [comment]
Julia Version 0.7.0-DEV.1816
Commit 1af1f5275c* (2017-09-17 15:48 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: Intel(R) Pentium(R) CPU G620 @ 2.60GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

**Comment by ararslan** [comment]
Can you post the contents of the path.jl file?

**Comment by DrKrar** [comment]
@ararslan , the path.jl content

> const BASE_JULIA_BIN="D:\Julia\Julia-0.7.0-DEV\bin"
> export BASE_JULIA_BIN
>
> const BASE_JULIA_SRC="D:\Julia\Julia-0.7.0-DEV\bin\../.."
> export BASE_JULIA_SRC

I think this file is written to the disk in the building process.

**Comment by ararslan** [comment]
Ah, I see. It needs the backslashes in the path to be escaped. I'll take a look.
