### ISSUE TITLE
Catching C++ exceptions

### ISSUE THREAD

**Issue by jtravs** [Keno/Cxx.jl#39]
I appreciate that this library is a work in progress (and is amazing already)! But is there currently any way to catch C++ exceptions and transfer them to julia? Currently julia simply segfaults.

I can imagine writing a macro that takes a C++ exception type and writes the required code to catch this exception and transfer it to julia; I might write such a thing; but I am wondering if this has already been thought about?

**Comment by Keno** [comment]
This is done.
