### ISSUE TITLE
issues with include search path

### ISSUE THREAD

**Issue by bfredl** [Keno/Cxx.jl#49]
Thanks for this very intresting project. It builds fine on arch linux, but when trying to run the examples it cannot include `iostream`. Arch linux seems to use the versioning scheme `4.9.2` which doen't  fit with `cxx_std_lib_version` which currently assumes `4.9` exactly and the layout is also slightly different.  ` $(gcc -print-prog-name=cc1plus) -v ` gives
```
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2
 /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/x86_64-unknown-linux-gnu
 /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/backward
 /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include
 /usr/local/include
 /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include-fixed
 /usr/include
```
After  copying and pasting these paths into `Cxx.jl` manually it works like a charm, but perhaps some library function in `libclang` could be used to determine the correct search path automatically, or something.

**Comment by Keno** [comment]
Clang has code to do this in `Driver`, but it's horribly convoluted and I don't really want to make header search that complicated. I'll add some code to handle your layout above and then add others on request as people encounter them.

**Comment by Keno** [comment]
I wrote some new header search code. I haven't tried it on Arch, but it's based on the one in clang so, I hope it should cover it. Let me know!

**Comment by swt30** [comment]
I'm using a system with environment modules. It has multiple versions of `gcc` in a subdirectory of  `/opt/`, with only a very old version actually in `/usr/`. Although I can set `ENV["CXXJL_ROOTDIR"]`, it doesn't mesh with the current approach, which assumes that `gcc` is in `$CXXJL_ROOTDIR/usr/`. It might be worthwhile relaxing this assumption.

```
#include "..." search starts here:
#include <...> search starts here:
 /opt/ioa/software/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0
 /opt/ioa/software/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu
 /opt/ioa/software/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward
 /opt/ioa/software/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include
 /usr/local/include
 /opt/ioa/software/gcc/5.3.0/include
 /opt/ioa/software/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed
 /usr/include
```
