### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by Keno** [Keno/Cxx.jl#56]
As @maxruby mentioned in #53, the code could use some more structure and documentation.

**Comment by Keno** [comment]
I spent the past couple of days cleaning up and documenting the code. The C++ side is still pretty messy and some new comments need to be written, but that can happen organically. If there's anything specific that's unclear, please let me know.

**Comment by maxruby** [comment]
Thanks!  It looks a lot better.  I will definitely dig into it.
