### ISSUE TITLE
Clang Version Support

### ISSUE THREAD

**Issue by sjkelly** [Keno/Cxx.jl#66]
I just learned yesterday LLVM and Clang are now on 3.7. Cxx seemed to work fine with 3.6. Would it make sense to branch for 3.6? Likewise, if we plan on supporting both 3.6 and 3.7, lines like the following: https://github.com/Keno/Cxx.jl/blob/a61efa02a95c70613ff568c2bf03a683e24a5545/src/initialization.jl#L257 need to be changed to handle multiple versions. What should the approach be here?

**Comment by sjkelly** [comment]
Optionally we can just stay bleeding edge and change the aforementioned line :)

**Comment by Keno** [comment]
Yes, I plan to stay on bleeding edge for at least another version, as I will be upstreaming more patches and don't want to have to implement workarounds here.

**Comment by sjkelly** [comment]
I support that approach!
