### ISSUE TITLE
Parsing Templates in @{v|r|p|cp}cpp_str

### ISSUE THREAD

**Issue by sjkelly** [Keno/Cxx.jl#72]
It seems like this would be really handy to have:
```
julia> vcpp"std::vector<ClipperLib::IntPoint>"
Cxx.CppValue{Cxx.CppBaseType{symbol("std::vector<ClipperLib::IntPoint>")},(false,false,false)}
```
when the real type signature after construction looks like:
```
Cxx.CppValue{Cxx.CppTemplate{Cxx.CppBaseType{symbol("std::vector")},(Cxx.CppValue{Cxx.CppBaseType{symbol("ClipperLib::IntPoint")},(false,false,false)},Cxx.CppValue{Cxx.CppTemplate{Cxx.CppBaseType{symbol("std::allocator")},(Cxx.CppValue{Cxx.CppBaseType{symbol("ClipperLib::IntPoint")},(false,false,false)},)},(false,false,false)})},(false,false,false)}
```
and is defined in C++ as: `typedef std::vector<IntPoint> Path;`

**Comment by Keno** [comment]
This one is tricky, because I really want those macros to be as simple as possible. In order to do full canonicalization, we'd have to call into Clang, which I'd been hoping to avoid. Not sure what to do yet. Will ponder.
