### ISSUE TITLE
Error in Yosemite

### ISSUE THREAD

**Issue by Kindpire** [Keno/Cxx.jl#76]
Hi All,

I'm trying to install Cxx.ji in Yosemite 10.10.2. Followed the instruction of Building Julia, I added these lines in Make.user.
override LLDB_VER=master
override LLVM_VER=svn
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override BUILD_LLDB=1
override USE_LLVM_SHLIB=1
override LLDB_DISABLE_PYTHON=1

However I found the following errors. 

llvm[7]: Compiling FormatManager.cpp for Release+Asserts build
mydirectory/julia/deps/llvm-svn/tools/lldb/source/DataFormatters/FormatManager.cpp:1582:5: error: 
      use of undeclared identifier 'AddCXXSummary'
    AddCXXSummary(cm_category_sp, lldb_private::formatters::CMTimeSummaryProvider, "CMTim...
    ^
1 error generated.
make[7]: *** [mydirectory/julia/deps/llvm-svn/build_Release+Asserts/tools/lldb/source/DataFormatters/Release+Asserts/FormatManager.o] Error 1
make[6]: *** [DataFormatters/.makeinstall] Error 2
make[5]: *** [install] Error 1
make[4]: *** [install] Error 1
make[3]: *** [install] Error 1
make[2]: *** [mydirectory/julia/usr/lib/libLLVMCodeGen.a] Error 2
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2

Any insights?

**Comment by Kindpire** [comment]
Well, for some unknown reason, I successfully builded julia0.4.0dev. However, when I Pkg.build(Cxx), it showed me:
INFO: Building Cxx
Tuning for julia installation at: /Users/pengfei/Development/julia/usr/bin
    LINK /Users/pengfei/.julia/Cxx/deps/usr/lib/libcxxffi.dylib
Undefined symbols for architecture x86_64:
  "lldb_private::PlatformAndroid::Initialize()", referenced from:
      lldb_private::Initialize() in liblldbInitAndLog.a(lldb.o)
  "lldb_private::PlatformAndroid::Terminate()", referenced from:
      lldb_private::Terminate() in liblldbInitAndLog.a(lldb.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [usr/lib/libcxxffi.dylib] Error 1
==========================[ ERROR: Cxx ]===============================
LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/Users/pengfei/Development/julia/usr/bin`, ProcessExited(2)) [2]
while loading /Users/pengfei/.julia/Cxx/deps/build.jl, in expression starting on line 16

=====================================================================

==========================[ BUILD ERRORS ]============================
WARNING: Cxx had build errors.

 - packages with build errors remain installed in /Users/pengfei/.julia
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

=======================================================================

**Comment by Keno** [comment]
Looks like it's missing platformandroid (there should be other platform libraries already there) from the link line in deps/BuildBoostrap.Makefile. I won't get to trying to fix it today, but see if you can fix it by adding that to the link line.

**Comment by Kindpire** [comment]
Thanks Keno, yes, I added -llldbPluginPlatformAndroid in ~/.julia/Cxx/deps/BuildBootstrap.Makefile, it showed:
julia> Pkg.build("Cxx")
INFO: Building Cxx
Tuning for julia installation at: /Users/pengfei/Development/julia/usr/bin
    CC /Users/pengfei/.julia/Cxx/deps/build/bootstrap.o
    LINK /Users/pengfei/.julia/Cxx/deps/usr/lib/libcxxffi.dylib
Not building debug library because corresponding julia DEBUG library does not exist.
To build, simply run the build again once the library at
/Users/pengfei/Development/julia/usr/bin/../../usr/lib/libjulia-debug.dylib
has been built.

But there won't be any error when I run "using Cxx"
And when I run the first example (display the number 52), it produced a warning:
WARNING: [a] concatenation is deprecated; use [a;] instead
 in depwarn at ./deprecated.jl:40
 in oldstyle_vcat_warning at ./abstractarray.jl:26
The number is 52

is this alright?
