### ISSUE TITLE
Eliminate Linux workarounds

### ISSUE THREAD

**Issue by sjkelly** [Keno/Cxx.jl#87]
This seems like an upstream issue. @Keno do you know if there is an issue for this?

**Comment by ihnorton** [comment]
http://reviews.llvm.org/D5431

**Comment by ihnorton** [comment]
Possibly relevant: http://reviews.llvm.org/D8991

**Comment by ihnorton** [comment]
Actually, I'm pretty sure that did the trick. I removed the local patch and got a successful `make` in `build_Release+Asserts`.
