### ISSUE TITLE
Compile error with llvm::Triple

### ISSUE THREAD

**Issue by sebastiang** [Keno/Cxx.jl#90]
Every few days I try to build Julia on OS X according to the instructions here and haven't succeeded yet.The latest error looks like it may be in Julia as relates to the latest LLVM. Is there a binary build available for Julia and Cxx.jl? They seem very fiddly to compile, which isn't unreasonable as they're aiming at the heads of multiple source trees! Thanks.

	    CC src/disasm.o
	disasm.cpp:339:40: error: reference to type 'const llvm::Triple' could not bind to an lvalue of type 'unsigned int'
	        TheTarget->createMCInstPrinter(OutputAsmVariant, *MAI, *MCII, *MRI, *STI);
	                                       ^~~~~~~~~~~~~~~~
	/Users/sebastian/dev/julia-cxx/usr/include/llvm/Support/TargetRegistry.h:411:54: note: passing argument to parameter 'T' here
	    MCInstPrinter *createMCInstPrinter(const Triple &T, unsigned SyntaxVariant,
	                                                     ^
	1 error generated.
	make[1]: *** [disasm.o] Error 1

**Comment by Keno** [comment]
Should be fixed on julia master. I've been meaning to get binaries out, but I'm not sure it's really worth the effort until Julia 0.4, LLVM/Clang 3.7.

**Comment by sebastiang** [comment]
That's done it and thanks! Perhaps we can get a Travis build of Julia plus
llvm going? Problem is they don't have any OS X support capacity at
present.

On Wednesday, April 1, 2015, Keno Fischer <notifications@github.com> wrote:

> Closed #90 <https://github.com/Keno/Cxx.jl/issues/90>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Keno/Cxx.jl/issues/90#event-270361140>.
>


-- 
*Sebastian Good*
