### ISSUE TITLE
LLVM not installed to custom folder

### ISSUE THREAD

**Issue by sebastiang** [Keno/Cxx.jl#91]
(On OS X) After a successful `make`, `./julia` starts Julia, but after `make install`, julia cannot be run from its target directory, failing with

    dyld: Library not loaded: @rpath/libLLVM-3.7svn.dylib
      Referenced from: /Users/sebastian/dev/julia-v0.4/bin/julia
      Reason: image not found
    Trace/BPT trap: 5

Indeed a `find . -name "*libLLVM*"` in the build directory finds many relevant files, but none seem to have made it into the install directory. The `Make.user` file has the following line in it along with the suggested lines from this project's README

    prefix=/Users/sebastian/dev/julia-v0.4

**Comment by ihnorton** [comment]
try
make -C deps install-llvm
and/or
make -C deps/llvm-svn/build_Release+Asserts install

**Comment by sebastiang** [comment]
Neither suggested install fixes the problem, I suspect this is better reported on the mainline Julia repo; I opened Julialang/julia#10849 over there.
