### ISSUE TITLE
String handling

### ISSUE THREAD

**Issue by Keno** [Keno/Cxx.jl#95]
Passing strings to C++ is a common task, but there's currently no good, safe way to do that.

**Comment by ScottPJones** [comment]
What currently are the problems with passing strings to C++?  (as you already know, string handling is important to me, and I may need to interface to C++ for some work I'm doing)

**Comment by Keno** [comment]
It's just not implemented very nicely in the type translation. Right now the only way to do it is basically:
```
C++> x->foo($(pointer(str)));
```
which is both unsafe (if `str` get garbage collected on the julia side) and not particularly user friendly. This issue was basically just a note on my todo list to implement it when I have the time.
