### ISSUE TITLE
Ubuntu 15.04: llvm/IR/ValueMap.h not found

### ISSUE THREAD

**Issue by jhasse** [Keno/Cxx.jl#96]
I've tried to build Cxx.jl on Ubuntu 15.04. This is what I did:
```bash
$ sudo apt install libedit-dev libncurses5-dev
$ git clone --depth=1 https://github.com/JuliaLang/julia
$ cd julia
$ echo "override LLDB_VER=master \
override LLVM_VER=svn \
override LLVM_ASSERTIONS=1 \
override BUILD_LLVM_CLANG=1 \
override BUILD_LLDB=1 \
override USE_LLVM_SHLIB=1 \
override LLDB_DISABLE_PYTHON=1" > Make.user
$ make -j4
$ ./julia -e 'Pkg.clone("https://github.com/Keno/Cxx.jl.git")'
$ ./julia -e 'Pkg.build("Cxx")'
```
and the last step gives me:
```
INFO: Building Cxx
Tuning for julia installation at: /home/jhasse/git/julia/usr/bin
    CC /home/jhasse/.julia/v0.4/Cxx/deps/build/bootstrap.o
../src/bootstrap.cpp:14:30: fatal error: llvm/IR/ValueMap.h: No such file or directory
 #include "llvm/IR/ValueMap.h"
                              ^
compilation terminated.
BuildBootstrap.Makefile:72: recipe for target 'build/bootstrap.o' failed
make: *** [build/bootstrap.o] Error 1
=================================[ ERROR: Cxx ]=================================

LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/home/jhasse/git/julia/usr/bin`, ProcessExited(2)) [2]
while loading /home/jhasse/.julia/v0.4/Cxx/deps/build.jl, in expression starting on line 16

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /home/jhasse/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by cndesantana** [comment]
Same error with me. I am using Julia version 0.4.0-dev+3735 (2015-03-09). Just tried to install Cxx by using the same commands as jhasse and got the same error message:

```
julia> Pkg.build("Cxx")
INFO: Building Cxx
Tuning for julia installation at: /home/cdesantana/Downloads/julia/usr/bin
    CC /home/cdesantana/.julia/v0.4/Cxx/deps/build/bootstrap.o
../src/bootstrap.cpp:14:30: fatal error: llvm/IR/ValueMap.h: No such file or directory
 #include "llvm/IR/ValueMap.h"
                              ^
compilation terminated.
make: *** [build/bootstrap.o] Error 1
====================================[ ERROR: Cxx ]=====================================

LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/home/cdesantana/Downloads/julia/usr/bin`, ProcessExited(2)) [2]
while loading /home/cdesantana/.julia/v0.4/Cxx/deps/build.jl, in expression starting on line 16

=======================================================================================

===================================[ BUILD ERRORS ]====================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /home/cdesantana/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

=======================================================================================

```

**Comment by elehcim** [comment]
Same error for me. I have Ubuntu 15.04 and julia version 0.5.0-dev+1000

Enabling verbosity in the make process:

    g++ -m64 -fno-rtti -DLIBRARY_EXPORTS -fPIC -O0 -g -std=c++11   -I~/julia/usr/bin/../../usr/include -I~/julia/usr/bin/../../src/support -I~/julia/usr/include -I~/julia/usr/bin/../../deps/srccache/llvm-3.3/tools/clang/lib -I~/julia/usr/bin/../../deps/llvm-3.3/tools/clang/lib -c ../src/bootstrap.cpp -o build/bootstrap.o
    ../src/bootstrap.cpp:14:30: fatal error: llvm/IR/ValueMap.h: No such file or directory
     #include "llvm/IR/ValueMap.h"

In `llvm/IR/` there are `Value.h` and `ValueSymbolTable.h`
Thinking of a file rename, I tried to substitute the include directive in src/bootstrap.cpp with both of the mentioned header files but then it fails `#include "clang/Sema/ScopeInfo.h"`

Actually, I don't have any of the following include folders (see `deps/BuildBootstrap.Makefile:8`)

    -I$(JULIAHOME)/deps/srccache/llvm-$(LLVM_VER)/tools/clang/lib \
    -I$(JULIAHOME)/deps/llvm-$(LLVM_VER)/tools/clang/lib

**Comment by elehcim** [comment]
Actually this was my fault. I didn't add the lines:

    override LLVM_GIT_URL_LLVM=https://github.com/JuliaLang/llvm.git
    override LLVM_GIT_URL_LLDB=https://github.com/JuliaLang/lldb.git
    override LLVM_GIT_URL_CLANG=https://github.com/JuliaLang/clang.git
    override LLVM_GIT_VER=kf/gallium
    override LLVM_GIT_VER_LLDB=kf/gallium
    override LLVM_GIT_VER_CLANG=kf/gallium

to Make.user

sorry for the noise. This error is not an issue.

**Comment by jhasse** [comment]
Yes, this can be fixed with the additional lines :)
