### ISSUE TITLE
Building with position independent code to use Qt

### ISSUE THREAD

**Issue by drewrobson** [Keno/Cxx.jl#98]
I ran into trouble with qttest.jl on `cxxinclude("QApplication", isAngled=true)`:

```
qglobal.h:1050:4: error: "You must build your code with position independent code if Qt was built with -reduce-relocations. "         "Compile your code with -fPIC or -fPIE."
```

This was using the Qt 5.4 binaries provided by the Qt Online Installer for Linux (and changing the paths in qttest.jl to point to ~/Qt/5.4/gcc_64/...)

I fixed it by adding the following to bootstrap.cpp:

```
Cxx->CI->getLangOpts().PICLevel = 2;
```

Maybe PICLevel could be exposed as an option to the user?

**Comment by Keno** [comment]
We can probably just set it unconditionally, since the generated code needs to be PIC anyway for JITting.
